export const DATA_NODES_LINKS = {
  nodes: [
    {
      text: "2 + 1 ≠ 3",
      id: 0,
    },
    {
      text: "Illogically Logical",
      id: 1,
    },
    {
      text: "Dynamic System",
      id: 2,
    },
    {
      text: "Nonequality",
      id: 3,
    },
    {
      text: "Not Equal",
      id: 4,
    },
    {
      text: "Static System",
      id: 5,
    },
    {
      text: "Double Thinking",
      id: 6,
    },
    {
      text: "Narrative Fallacy",
      id: 7,
    },
    {
      text: "Number Theory",
      id: 8,
    },
    {
      text: "2 + 1 = 3",
      id: 9,
    },
    {
      text: "Equality",
      id: 10,
    },
    {
      text: "Modular Arithmetic",
      id: 11,
    },
    {
      text: "Prime Numbers",
      id: 12,
    },
    {
      text: "Equation",
      id: 13,
    },
    {
      text: "Nonequlibrium",
      id: 14,
    },
    {
      text: "Crowd Psychology",
      id: 15,
    },
    {
      text: "Performance Art",
      id: 16,
    },
    {
      text: "Joker",
      id: 17,
    },
    {
      text: "Behaviour Economics",
      id: 18,
    },
    {
      text: "Nonsense",
      id: 19,
    },
    {
      text: "Blockchain",
      id: 20,
    },
    {
      text: "Action Painting",
      id: 21,
    },
    {
      text: "Monumental Art",
      id: 22,
    },
    {
      text: "Unexpected",
      id: 23,
    },
    {
      text: "Gaussian Distribution",
      id: 24,
    },
    {
      text: "AI",
      id: 25,
    },
    {
      text: "Building Unusable Runway",
      id: 26,
    },
    {
      text: "False Justification",
      id: 27,
    },
    {
      text: "Narrative",
      id: 28,
    },
    {
      text: "NFT",
      id: 29,
    },
    {
      text: "Inflation",
      id: 30,
    },
    {
      text: "Probability",
      id: 31,
    },
    {
      text: "Logically Illogical",
      id: 32,
    },
    {
      text: "Human Logics",
      id: 33,
    },
    {
      text: "Bitcoin",
      id: 34,
    },
    {
      text: "Landmark",
      id: 35,
    },
    {
      text: "Berlin",
      id: 36,
    },
    {
      text: "Climate Change",
      id: 37,
    },
    {
      text: "Black Swan",
      id: 38,
    },
    {
      text: "Conceptual Art",
      id: 39,
    },
    {
      text: "Pop Art",
      id: 40,
    },
    {
      text: "Hyperobject",
      id: 41,
    },
    {
      text: "Land Art",
      id: 42,
    },
    {
      text: "Environment",
      id: 43,
    },
    {
      text: "Industry",
      id: 44,
    },
    {
      text: "Efficiency",
      id: 45,
    },
    {
      text: "JFK Airport",
      id: 46,
    },
    {
      text: "Airport",
      id: 47,
    },
    {
      text: "John F. Kennedy",
      id: 48,
    },
    {
      text: "Airplane",
      id: 49,
    },
    {
      text: "Seoul",
      id: 50,
    },
    {
      text: "New York",
      id: 51,
    },
    {
      text: "Hyde Park",
      id: 52,
    },
    {
      text: "Downing 10",
      id: 53,
    },
    {
      text: "Churchill",
      id: 54,
    },
    {
      text: "London",
      id: 55,
    },
    {
      text: "Green Park",
      id: 56,
    },
    {
      text: "Tour Eiffel",
      id: 57,
    },
    {
      text: "Parc de la Villette",
      id: 58,
    },
    {
      text: "Paris",
      id: 59,
    },
    {
      text: "Namsan",
      id: 60,
    },
    {
      text: "Memorial to the Murdered Jews of Europe",
      id: 61,
    },
    {
      text: "Arc de Triomphe",
      id: 62,
    },
    {
      text: "Neoliberalism",
      id: 63,
    },
    {
      text: "Speech",
      id: 64,
    },
    {
      text: "Tempelhof Park",
      id: 65,
    },
    {
      text: "Illogic Inherent in Logic",
      id: 66,
    },
    {
      text: "Brandenburg Gate",
      id: 67,
    },
    {
      text: "Ronald Reagan",
      id: 68,
    },
    {
      text: "Berlin Wall",
      id: 69,
    },
    {
      text: "Tear Down This Wall",
      id: 70,
    },
    {
      text: "Ich bin ein Berliner",
      id: 71,
    },
    {
      text: "Peace of our time",
      id: 72,
    },
    {
      text: "Peace",
      id: 73,
    },
    {
      text: "Chamberlain",
      id: 74,
    },
    {
      text: "White Noise",
      id: 75,
    },
    {
      text: "Appeasement",
      id: 76,
    },
    {
      text: "Munich Agreement",
      id: 77,
    },
    {
      text: "Germania Berlin",
      id: 78,
    },
    {
      text: "War and Peace",
      id: 79,
    },
    {
      text: "Hitler",
      id: 80,
    },
    {
      text: "Totalitarianism",
      id: 81,
    },
    {
      text: "Dostoyevsky",
      id: 82,
    },
    {
      text: "1984",
      id: 83,
    },
    {
      text: "Notes from Underground",
      id: 84,
    },
    {
      text: "2 X 2 = 5",
      id: 85,
    },
    {
      text: "Tolstoy",
      id: 86,
    },
    {
      text: "Soviet Union",
      id: 87,
    },
    {
      text: "Peace Treaty",
      id: 88,
    },
    {
      text: "Treaty of Versailles",
      id: 89,
    },
    {
      text: "Compiegne Wagon",
      id: 90,
    },
    {
      text: "Inequality",
      id: 91,
    },
    {
      text: "Propaganda",
      id: 92,
    },
    {
      text: "World War I",
      id: 93,
    },
    {
      text: "Nonequilibrium",
      id: 94,
    },
    {
      text: "Nonlinear",
      id: 95,
    },
    {
      text: "World is not equal",
      id: 96,
    },
    {
      text: "Entropy",
      id: 97,
    },
    {
      text: "German Hyperinflation",
      id: 98,
    },
    {
      text: "The Butterfly Effect",
      id: 99,
    },
    {
      text: "Torture",
      id: 100,
    },
    {
      text: "Cold War",
      id: 101,
    },
    {
      text: "Pablo Picasso",
      id: 102,
    },
    {
      text: "Modernism",
      id: 103,
    },
    {
      text: "Korean War",
      id: 104,
    },
    {
      text: "Dadaism",
      id: 105,
    },
    {
      text: "Postmodernism",
      id: 106,
    },
    {
      text: "Limitation of Logic",
      id: 107,
    },
    {
      text: "Cubism",
      id: 108,
    },
    {
      text: "Berlin Blockade",
      id: 109,
    },
    {
      text: "Berlin Airlift",
      id: 110,
    },
    {
      text: "Gravity",
      id: 111,
    },
    {
      text: "Newtonian Physics",
      id: 112,
    },
    {
      text: "Invention of Airplane",
      id: 113,
    },
    {
      text: "Industrial Revolution",
      id: 114,
    },
    {
      text: "Going Against Gravity",
      id: 115,
    },
    {
      text: "The Use of Gravity",
      id: 116,
    },
    {
      text: "Atomic Bomb",
      id: 117,
    },
    {
      text: "Postmodernity",
      id: 118,
    },
    {
      text: "Quantum Physics",
      id: 119,
    },
    {
      text: "Modern Logics",
      id: 120,
    },
    {
      text: "Going Beyond Gravity",
      id: 121,
    },
    {
      text: "Theory of Relativity",
      id: 122,
    },
    {
      text: "Runway",
      id: 123,
    },
    {
      text: "Useless is Useful",
      id: 124,
    },
    {
      text: "World War II",
      id: 125,
    },
    {
      text: "Nazi Germany",
      id: 126,
    },
    {
      text: "Holocaust",
      id: 127,
    },
    {
      text: "Tempelhof Airport",
      id: 128,
    },
    {
      text: "Building Third Runway",
      id: 129,
    },
    {
      text: "Berlin Nonequality",
      id: 130,
    },
    {
      text: "≠",
      id: 131,
    },
    {
      text: "Not Equal",
      id: 132,
    },
  ],
  links: [
    {
      source: "2 + 1 ≠ 3",
      target: "Illogically Logical",
      value: 7,
      id: 0,
      isCycle: false,
    },
    {
      source: "Illogically Logical",
      target: "Tempelhof Airport",
      value: 16,
      id: 100,
      isCycle: false,
    },
    {
      source: "Dynamic System",
      target: "Static System",
      value: 4,
      id: 200,
      isCycle: false,
    },
    {
      source: "Dynamic System",
      target: "Equality",
      value: 5,
      id: 201,
      isCycle: false,
    },
    {
      source: "Dynamic System",
      target: "Nonequality",
      value: 7,
      id: 202,
      isCycle: false,
    },
    {
      source: "Nonequality",
      target: "Nonequlibrium",
      value: 10,
      id: 300,
      isCycle: false,
    },
    {
      source: "Nonequality",
      target: "Dynamic System",
      value: 7,
      id: 301,
      isCycle: false,
    },
    {
      source: "Nonequality",
      target: "Berlin Nonequality",
      value: 16,
      id: 302,
      isCycle: false,
    },
    {
      source: "Nonequality",
      target: "Berlin Wall",
      value: 10,
      id: 303,
      isCycle: false,
    },
    {
      source: "Nonequality",
      target: "World War II",
      value: 10,
      id: 304,
      isCycle: false,
    },
    {
      source: "Not Equal",
      target: "Berlin Nonequality",
      value: 50,
      id: 400,
      isCycle: true,
    },
    {
      source: "Not Equal",
      target: "Nonequlibrium",
      value: 16,
      id: 401,
      isCycle: true,
    },
    {
      source: "Static System",
      target: "Equality",
      value: 4,
      id: 500,
      isCycle: false,
    },
    {
      source: "Static System",
      target: "Human Logics",
      value: 4,
      id: 501,
      isCycle: false,
    },
    {
      source: "Static System",
      target: "2 + 1 = 3",
      value: 4,
      id: 502,
      isCycle: false,
    },
    {
      source: "Double Thinking",
      target: "Illogically Logical",
      value: 7,
      id: 600,
      isCycle: false,
    },
    {
      source: "Double Thinking",
      target: "2 + 1 = 3",
      value: 5,
      id: 601,
      isCycle: false,
    },
    {
      source: "Double Thinking",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 602,
      isCycle: false,
    },
    {
      source: "Double Thinking",
      target: "1984",
      value: 4,
      id: 603,
      isCycle: false,
    },
    {
      source: "Narrative Fallacy",
      target: "Illogically Logical",
      value: 7,
      id: 700,
      isCycle: false,
    },
    {
      source: "Narrative Fallacy",
      target: "2 + 1 = 3",
      value: 5,
      id: 701,
      isCycle: false,
    },
    {
      source: "Narrative Fallacy",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 702,
      isCycle: false,
    },
    {
      source: "Number Theory",
      target: "Modular Arithmetic",
      value: 3,
      id: 800,
      isCycle: false,
    },
    {
      source: "Number Theory",
      target: "Human Logics",
      value: 4,
      id: 801,
      isCycle: false,
    },
    {
      source: "Number Theory",
      target: "Prime Numbers",
      value: 3,
      id: 802,
      isCycle: false,
    },
    {
      source: "2 + 1 = 3",
      target: "Illogically Logical",
      value: 7,
      id: 900,
      isCycle: false,
    },
    {
      source: "2 + 1 = 3",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 901,
      isCycle: false,
    },
    {
      source: "Equality",
      target: "Equation",
      value: 4,
      id: 1000,
      isCycle: false,
    },
    {
      source: "Equality",
      target: "2 + 1 = 3",
      value: 5,
      id: 1001,
      isCycle: false,
    },
    {
      source: "Equality",
      target: "Human Logics",
      value: 5,
      id: 1002,
      isCycle: false,
    },
    {
      source: "Equality",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 1003,
      isCycle: false,
    },
    {
      source: "Equality",
      target: "Nonequality",
      value: 7,
      id: 1004,
      isCycle: false,
    },
    {
      source: "Modular Arithmetic",
      target: "2 + 1 ≠ 3",
      value: 4,
      id: 1100,
      isCycle: false,
    },
    {
      source: "Modular Arithmetic",
      target: "2 + 1 = 3",
      value: 4,
      id: 1101,
      isCycle: false,
    },
    {
      source: "Prime Numbers",
      target: "Number Theory",
      value: 3,
      id: 1200,
      isCycle: false,
    },
    {
      source: "Prime Numbers",
      target: "2 + 1 ≠ 3",
      value: 4,
      id: 1201,
      isCycle: false,
    },
    {
      source: "Prime Numbers",
      target: "Bitcoin",
      value: 4,
      id: 1202,
      isCycle: false,
    },
    {
      source: "Prime Numbers",
      target: "Blockchain",
      value: 3,
      id: 1203,
      isCycle: false,
    },
    {
      source: "Equation",
      target: "Equality",
      value: 4,
      id: 1300,
      isCycle: false,
    },
    {
      source: "Equation",
      target: "2 + 1 = 3",
      value: 4,
      id: 1301,
      isCycle: false,
    },
    {
      source: "Equation",
      target: "2 + 1 ≠ 3",
      value: 4,
      id: 1302,
      isCycle: false,
    },
    {
      source: "Nonequlibrium",
      target: "Berlin Nonequality",
      value: 16,
      id: 1400,
      isCycle: false,
    },
    {
      source: "Nonequlibrium",
      target: "Dynamic System",
      value: 7,
      id: 1401,
      isCycle: false,
    },
    {
      source: "Crowd Psychology",
      target: "Illogically Logical",
      value: 7,
      id: 1500,
      isCycle: false,
    },
    {
      source: "Crowd Psychology",
      target: "Behaviour Economics",
      value: 5,
      id: 1501,
      isCycle: false,
    },
    {
      source: "Crowd Psychology",
      target: "Propaganda",
      value: 7,
      id: 1502,
      isCycle: false,
    },
    {
      source: "Crowd Psychology",
      target: "Landmark",
      value: 7,
      id: 1503,
      isCycle: false,
    },
    {
      source: "Performance Art",
      target: "Building Third Runway",
      value: 16,
      id: 1600,
      isCycle: false,
    },
    {
      source: "Performance Art",
      target: "Berlin Nonequality",
      value: 16,
      id: 1601,
      isCycle: false,
    },
    {
      source: "Joker",
      target: "Illogically Logical",
      value: 7,
      id: 1700,
      isCycle: false,
    },
    {
      source: "Joker",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 1701,
      isCycle: false,
    },
    {
      source: "Behaviour Economics",
      target: "Narrative Fallacy",
      value: 5,
      id: 1800,
      isCycle: false,
    },
    {
      source: "Behaviour Economics",
      target: "Illogically Logical",
      value: 7,
      id: 1801,
      isCycle: false,
    },
    {
      source: "Nonsense",
      target: "Berlin Nonequality",
      value: 16,
      id: 1900,
      isCycle: false,
    },
    {
      source: "Nonsense",
      target: "2 + 1 ≠ 3",
      value: 7,
      id: 1901,
      isCycle: false,
    },
    {
      source: "Blockchain",
      target: "NFT",
      value: 4,
      id: 2000,
      isCycle: false,
    },
    {
      source: "Blockchain",
      target: "Bitcoin",
      value: 4,
      id: 2001,
      isCycle: false,
    },
    {
      source: "Blockchain",
      target: "Inflation",
      value: 4,
      id: 2002,
      isCycle: false,
    },
    {
      source: "Blockchain",
      target: "Logically Illogical",
      value: 4,
      id: 2003,
      isCycle: false,
    },
    {
      source: "Blockchain",
      target: "Crowd Psychology",
      value: 4,
      id: 2004,
      isCycle: false,
    },
    {
      source: "Blockchain",
      target: "Prime Numbers",
      value: 3,
      id: 2005,
      isCycle: false,
    },
    {
      source: "Action Painting",
      target: "Pop Art",
      value: 7,
      id: 2100,
      isCycle: false,
    },
    {
      source: "Action Painting",
      target: "Conceptual Art",
      value: 7,
      id: 2101,
      isCycle: false,
    },
    {
      source: "Action Painting",
      target: "Postmodernism",
      value: 5,
      id: 2102,
      isCycle: false,
    },
    {
      source: "Action Painting",
      target: "Modernism",
      value: 4,
      id: 2103,
      isCycle: false,
    },
    {
      source: "Monumental Art",
      target: "Building Unusable Runway",
      value: 7,
      id: 2200,
      isCycle: false,
    },
    {
      source: "Monumental Art",
      target: "Memorial to the Murdered Jews of Europe",
      value: 5,
      id: 2201,
      isCycle: false,
    },
    {
      source: "Unexpected",
      target: "Probability",
      value: 5,
      id: 2300,
      isCycle: false,
    },
    {
      source: "Unexpected",
      target: "Narrative Fallacy",
      value: 5,
      id: 2301,
      isCycle: false,
    },
    {
      source: "Unexpected",
      target: "Building Unusable Runway",
      value: 7,
      id: 2302,
      isCycle: false,
    },
    {
      source: "Gaussian Distribution",
      target: "Black Swan",
      value: 4,
      id: 2400,
      isCycle: false,
    },
    {
      source: "Gaussian Distribution",
      target: "Probability",
      value: 4,
      id: 2401,
      isCycle: false,
    },
    {
      source: "Gaussian Distribution",
      target: "Narrative Fallacy",
      value: 4,
      id: 2402,
      isCycle: false,
    },
    {
      source: "Gaussian Distribution",
      target: "AI",
      value: 3,
      id: 2403,
      isCycle: false,
    },
    {
      source: "Gaussian Distribution",
      target: "Logically Illogical",
      value: 4,
      id: 2404,
      isCycle: false,
    },
    {
      source: "Gaussian Distribution",
      target: "Limitation of Logic",
      value: 4,
      id: 2405,
      isCycle: false,
    },
    {
      source: "AI",
      target: "Gaussian Distribution",
      value: 3,
      id: 2500,
      isCycle: false,
    },
    {
      source: "AI",
      target: "NFT",
      value: 4,
      id: 2501,
      isCycle: false,
    },
    {
      source: "AI",
      target: "Limitation of Logic",
      value: 4,
      id: 2502,
      isCycle: false,
    },
    {
      source: "AI",
      target: "Human Logics",
      value: 4,
      id: 2503,
      isCycle: false,
    },
    {
      source: "Building Unusable Runway",
      target: "Performance Art",
      value: 10,
      id: 2600,
      isCycle: false,
    },
    {
      source: "Building Unusable Runway",
      target: "Building Third Runway",
      value: 16,
      id: 2601,
      isCycle: false,
    },
    {
      source: "Building Unusable Runway",
      target: "Illogically Logical",
      value: 10,
      id: 2602,
      isCycle: false,
    },
    {
      source: "Building Unusable Runway",
      target: "Monumental Art",
      value: 7,
      id: 2603,
      isCycle: false,
    },
    {
      source: "False Justification",
      target: "Logically Illogical",
      value: 5,
      id: 2700,
      isCycle: false,
    },
    {
      source: "False Justification",
      target: "2 + 1 = 3",
      value: 5,
      id: 2701,
      isCycle: false,
    },
    {
      source: "False Justification",
      target: "Narrative Fallacy",
      value: 5,
      id: 2702,
      isCycle: false,
    },
    {
      source: "False Justification",
      target: "Propaganda",
      value: 7,
      id: 2703,
      isCycle: false,
    },
    {
      source: "Narrative",
      target: "Narrative Fallacy",
      value: 5,
      id: 2800,
      isCycle: false,
    },
    {
      source: "Narrative",
      target: "False Justification",
      value: 5,
      id: 2801,
      isCycle: false,
    },
    {
      source: "Narrative",
      target: "Illogic Inherent in Logic",
      value: 5,
      id: 2802,
      isCycle: false,
    },
    {
      source: "Narrative",
      target: "Propaganda",
      value: 7,
      id: 2803,
      isCycle: false,
    },
    {
      source: "NFT",
      target: "Bitcoin",
      value: 5,
      id: 2900,
      isCycle: false,
    },
    {
      source: "NFT",
      target: "Illogically Logical",
      value: 7,
      id: 2901,
      isCycle: false,
    },
    {
      source: "NFT",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 2902,
      isCycle: false,
    },
    {
      source: "NFT",
      target: "Crowd Psychology",
      value: 5,
      id: 2903,
      isCycle: false,
    },
    {
      source: "Inflation",
      target: "Illogically Logical",
      value: 7,
      id: 3000,
      isCycle: false,
    },
    {
      source: "Inflation",
      target: "Hyperobject",
      value: 5,
      id: 3001,
      isCycle: false,
    },
    {
      source: "Inflation",
      target: "German Hyperinflation",
      value: 5,
      id: 3002,
      isCycle: false,
    },
    {
      source: "Inflation",
      target: "Behaviour Economics",
      value: 5,
      id: 3003,
      isCycle: false,
    },
    {
      source: "Probability",
      target: "Gaussian Distribution",
      value: 4,
      id: 3100,
      isCycle: false,
    },
    {
      source: "Probability",
      target: "Black Swan",
      value: 5,
      id: 3101,
      isCycle: false,
    },
    {
      source: "Probability",
      target: "Dynamic System",
      value: 5,
      id: 3102,
      isCycle: false,
    },
    {
      source: "Probability",
      target: "Nonequlibrium",
      value: 7,
      id: 3103,
      isCycle: false,
    },
    {
      source: "Logically Illogical",
      target: "Illogically Logical",
      value: 7,
      id: 3200,
      isCycle: false,
    },
    {
      source: "Logically Illogical",
      target: "Illogic Inherent in Logic",
      value: 5,
      id: 3201,
      isCycle: false,
    },
    {
      source: "Logically Illogical",
      target: "2 + 1 = 3",
      value: 5,
      id: 3202,
      isCycle: false,
    },
    {
      source: "Logically Illogical",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 3203,
      isCycle: false,
    },
    {
      source: "Human Logics",
      target: "Illogically Logical",
      value: 7,
      id: 3300,
      isCycle: false,
    },
    {
      source: "Human Logics",
      target: "2 + 1 = 3",
      value: 5,
      id: 3301,
      isCycle: false,
    },
    {
      source: "Human Logics",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 3302,
      isCycle: false,
    },
    {
      source: "Human Logics",
      target: "Illogic Inherent in Logic",
      value: 5,
      id: 3303,
      isCycle: false,
    },
    {
      source: "Human Logics",
      target: "Nazi Germany",
      value: 7,
      id: 3304,
      isCycle: false,
    },
    {
      source: "Bitcoin",
      target: "NFT",
      value: 5,
      id: 3400,
      isCycle: false,
    },
    {
      source: "Bitcoin",
      target: "Blockchain",
      value: 4,
      id: 3401,
      isCycle: false,
    },
    {
      source: "Bitcoin",
      target: "Logically Illogical",
      value: 5,
      id: 3402,
      isCycle: false,
    },
    {
      source: "Bitcoin",
      target: "Illogically Logical",
      value: 7,
      id: 3403,
      isCycle: false,
    },
    {
      source: "Bitcoin",
      target: "Behaviour Economics",
      value: 5,
      id: 3404,
      isCycle: false,
    },
    {
      source: "Landmark",
      target: "Berlin Nonequality",
      value: 16,
      id: 3500,
      isCycle: false,
    },
    {
      source: "Landmark",
      target: "Tempelhof Airport",
      value: 16,
      id: 3501,
      isCycle: false,
    },
    {
      source: "Landmark",
      target: "Memorial to the Murdered Jews of Europe",
      value: 7,
      id: 3502,
      isCycle: false,
    },
    {
      source: "Landmark",
      target: "Land Art",
      value: 10,
      id: 3503,
      isCycle: false,
    },
    {
      source: "Berlin",
      target: "Berlin Nonequality",
      value: 16,
      id: 3600,
      isCycle: false,
    },
    {
      source: "Berlin",
      target: "Tempelhof Airport",
      value: 16,
      id: 3601,
      isCycle: false,
    },
    {
      source: "Berlin",
      target: "Berlin Airlift",
      value: 10,
      id: 3602,
      isCycle: false,
    },
    {
      source: "Berlin",
      target: "Berlin Wall",
      value: 10,
      id: 3603,
      isCycle: false,
    },
    {
      source: "Climate Change",
      target: "Hyperobject",
      value: 5,
      id: 3700,
      isCycle: false,
    },
    {
      source: "Climate Change",
      target: "Human Logics",
      value: 5,
      id: 3701,
      isCycle: false,
    },
    {
      source: "Climate Change",
      target: "Illogically Logical",
      value: 7,
      id: 3702,
      isCycle: false,
    },
    {
      source: "Climate Change",
      target: "Environment",
      value: 5,
      id: 3703,
      isCycle: false,
    },
    {
      source: "Climate Change",
      target: "Black Swan",
      value: 5,
      id: 3704,
      isCycle: false,
    },
    {
      source: "Black Swan",
      target: "Hyperobject",
      value: 5,
      id: 3800,
      isCycle: false,
    },
    {
      source: "Black Swan",
      target: "Probability",
      value: 5,
      id: 3801,
      isCycle: false,
    },
    {
      source: "Black Swan",
      target: "Gaussian Distribution",
      value: 4,
      id: 3802,
      isCycle: false,
    },
    {
      source: "Black Swan",
      target: "Unexpected",
      value: 5,
      id: 3803,
      isCycle: false,
    },
    {
      source: "Black Swan",
      target: "Dynamic System",
      value: 5,
      id: 3804,
      isCycle: false,
    },
    {
      source: "Black Swan",
      target: "Nonequlibrium",
      value: 7,
      id: 3805,
      isCycle: false,
    },
    {
      source: "Black Swan",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 3806,
      isCycle: false,
    },
    {
      source: "Black Swan",
      target: "Human Logics",
      value: 5,
      id: 3807,
      isCycle: false,
    },
    {
      source: "Black Swan",
      target: "Narrative Fallacy",
      value: 5,
      id: 3808,
      isCycle: false,
    },
    {
      source: "Conceptual Art",
      target: "Berlin Nonequality",
      value: 16,
      id: 3900,
      isCycle: false,
    },
    {
      source: "Conceptual Art",
      target: "Building Third Runway",
      value: 16,
      id: 3901,
      isCycle: false,
    },
    {
      source: "Conceptual Art",
      target: "Building Unusable Runway",
      value: 10,
      id: 3902,
      isCycle: false,
    },
    {
      source: "Conceptual Art",
      target: "Performance Art",
      value: 10,
      id: 3903,
      isCycle: false,
    },
    {
      source: "Conceptual Art",
      target: "Land Art",
      value: 10,
      id: 3904,
      isCycle: false,
    },
    {
      source: "Conceptual Art",
      target: "Postmodernism",
      value: 7,
      id: 3905,
      isCycle: false,
    },
    {
      source: "Pop Art",
      target: "Berlin Nonequality",
      value: 16,
      id: 4000,
      isCycle: false,
    },
    {
      source: "Pop Art",
      target: "Building Third Runway",
      value: 16,
      id: 4001,
      isCycle: false,
    },
    {
      source: "Pop Art",
      target: "Conceptual Art",
      value: 10,
      id: 4002,
      isCycle: false,
    },
    {
      source: "Pop Art",
      target: "Postmodernism",
      value: 7,
      id: 4003,
      isCycle: false,
    },
    {
      source: "Pop Art",
      target: "Modernism",
      value: 5,
      id: 4004,
      isCycle: false,
    },
    {
      source: "Hyperobject",
      target: "Climate Change",
      value: 5,
      id: 4100,
      isCycle: false,
    },
    {
      source: "Hyperobject",
      target: "Human Logics",
      value: 5,
      id: 4101,
      isCycle: false,
    },
    {
      source: "Hyperobject",
      target: "Illogically Logical",
      value: 7,
      id: 4102,
      isCycle: false,
    },
    {
      source: "Hyperobject",
      target: "Dynamic System",
      value: 5,
      id: 4103,
      isCycle: false,
    },
    {
      source: "Hyperobject",
      target: "Nonequlibrium",
      value: 7,
      id: 4104,
      isCycle: false,
    },
    {
      source: "Hyperobject",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 4105,
      isCycle: false,
    },
    {
      source: "Land Art",
      target: "Berlin Nonequality",
      value: 16,
      id: 4200,
      isCycle: false,
    },
    {
      source: "Land Art",
      target: "Building Third Runway",
      value: 16,
      id: 4201,
      isCycle: false,
    },
    {
      source: "Land Art",
      target: "Building Unusable Runway",
      value: 10,
      id: 4202,
      isCycle: false,
    },
    {
      source: "Land Art",
      target: "Landmark",
      value: 10,
      id: 4203,
      isCycle: false,
    },
    {
      source: "Environment",
      target: "Climate Change",
      value: 5,
      id: 4300,
      isCycle: false,
    },
    {
      source: "Environment",
      target: "Hyperobject",
      value: 5,
      id: 4301,
      isCycle: false,
    },
    {
      source: "Environment",
      target: "Nonequlibrium",
      value: 7,
      id: 4302,
      isCycle: false,
    },
    {
      source: "Environment",
      target: "Dynamic System",
      value: 5,
      id: 4303,
      isCycle: false,
    },
    {
      source: "Environment",
      target: "2 + 1 ≠ 3",
      value: 5,
      id: 4304,
      isCycle: false,
    },
    {
      source: "Industry",
      target: "Industrial Revolution",
      value: 3,
      id: 4400,
      isCycle: false,
    },
    {
      source: "Industry",
      target: "Efficiency",
      value: 4,
      id: 4401,
      isCycle: false,
    },
    {
      source: "Efficiency",
      target: "Modern Logics",
      value: 4,
      id: 4500,
      isCycle: false,
    },
    {
      source: "Efficiency",
      target: "Postmodernity",
      value: 5,
      id: 4501,
      isCycle: false,
    },
    {
      source: "Efficiency",
      target: "Useless is Useful",
      value: 7,
      id: 4502,
      isCycle: false,
    },
    {
      source: "JFK Airport",
      target: "Airport",
      value: 7,
      id: 4600,
      isCycle: false,
    },
    {
      source: "JFK Airport",
      target: "New York",
      value: 5,
      id: 4601,
      isCycle: false,
    },
    {
      source: "JFK Airport",
      target: "Runway",
      value: 7,
      id: 4602,
      isCycle: false,
    },
    {
      source: "Airport",
      target: "Runway",
      value: 10,
      id: 4700,
      isCycle: false,
    },
    {
      source: "Airport",
      target: "Airplane",
      value: 5,
      id: 4701,
      isCycle: false,
    },
    {
      source: "Airport",
      target: "Tempelhof Airport",
      value: 16,
      id: 4702,
      isCycle: false,
    },
    {
      source: "John F. Kennedy",
      target: "JFK Airport",
      value: 4,
      id: 4800,
      isCycle: false,
    },
    {
      source: "John F. Kennedy",
      target: "Ich bin ein Berliner",
      value: 4,
      id: 4801,
      isCycle: false,
    },
    {
      source: "Airplane",
      target: "Going Beyond Gravity",
      value: 3,
      id: 4900,
      isCycle: false,
    },
    {
      source: "Airplane",
      target: "Invention of Airplane",
      value: 4,
      id: 4901,
      isCycle: false,
    },
    {
      source: "Airplane",
      target: "Industry",
      value: 3,
      id: 4902,
      isCycle: false,
    },
    {
      source: "Seoul",
      target: "Korean War",
      value: 5,
      id: 5000,
      isCycle: false,
    },
    {
      source: "Seoul",
      target: "Berlin",
      value: 7,
      id: 5001,
      isCycle: false,
    },
    {
      source: "Seoul",
      target: "Efficiency",
      value: 5,
      id: 5002,
      isCycle: false,
    },
    {
      source: "Seoul",
      target: "Namsan",
      value: 5,
      id: 5003,
      isCycle: false,
    },
    {
      source: "New York",
      target: "London",
      value: 5,
      id: 5100,
      isCycle: false,
    },
    {
      source: "New York",
      target: "Paris",
      value: 5,
      id: 5101,
      isCycle: false,
    },
    {
      source: "New York",
      target: "Seoul",
      value: 5,
      id: 5102,
      isCycle: false,
    },
    {
      source: "New York",
      target: "Berlin",
      value: 7,
      id: 5103,
      isCycle: false,
    },
    {
      source: "New York",
      target: "Joker",
      value: 5,
      id: 5104,
      isCycle: false,
    },
    {
      source: "Hyde Park",
      target: "Tempelhof Park",
      value: 7,
      id: 5200,
      isCycle: false,
    },
    {
      source: "Hyde Park",
      target: "Parc de la Villette",
      value: 5,
      id: 5201,
      isCycle: false,
    },
    {
      source: "Hyde Park",
      target: "Green Park",
      value: 5,
      id: 5202,
      isCycle: false,
    },
    {
      source: "Hyde Park",
      target: "Namsan",
      value: 5,
      id: 5203,
      isCycle: false,
    },
    {
      source: "Downing 10",
      target: "Churchill",
      value: 4,
      id: 5300,
      isCycle: false,
    },
    {
      source: "Downing 10",
      target: "Chamberlain",
      value: 4,
      id: 5301,
      isCycle: false,
    },
    {
      source: "Churchill",
      target: "World War II",
      value: 7,
      id: 5400,
      isCycle: false,
    },
    {
      source: "Churchill",
      target: "Hitler",
      value: 5,
      id: 5401,
      isCycle: false,
    },
    {
      source: "Churchill",
      target: "Peace",
      value: 3,
      id: 5402,
      isCycle: false,
    },
    {
      source: "London",
      target: "Hyde Park",
      value: 5,
      id: 5500,
      isCycle: false,
    },
    {
      source: "London",
      target: "Green Park",
      value: 5,
      id: 5501,
      isCycle: false,
    },
    {
      source: "London",
      target: "Downing 10",
      value: 4,
      id: 5502,
      isCycle: false,
    },
    {
      source: "London",
      target: "Berlin",
      value: 7,
      id: 5503,
      isCycle: false,
    },
    {
      source: "Green Park",
      target: "Tempelhof Park",
      value: 7,
      id: 5600,
      isCycle: false,
    },
    {
      source: "Green Park",
      target: "Parc de la Villette",
      value: 5,
      id: 5601,
      isCycle: false,
    },
    {
      source: "Green Park",
      target: "Hyde Park",
      value: 5,
      id: 5602,
      isCycle: false,
    },
    {
      source: "Green Park",
      target: "Namsan",
      value: 5,
      id: 5603,
      isCycle: false,
    },
    {
      source: "Tour Eiffel",
      target: "Arc de Triomphe",
      value: 10,
      id: 5700,
      isCycle: false,
    },
    {
      source: "Tour Eiffel",
      target: "Landmark",
      value: 10,
      id: 5701,
      isCycle: false,
    },
    {
      source: "Tour Eiffel",
      target: "Tempelhof Airport",
      value: 16,
      id: 5702,
      isCycle: false,
    },
    {
      source: "Parc de la Villette",
      target: "Tempelhof Park",
      value: 7,
      id: 5800,
      isCycle: false,
    },
    {
      source: "Parc de la Villette",
      target: "Green Park",
      value: 5,
      id: 5801,
      isCycle: false,
    },
    {
      source: "Parc de la Villette",
      target: "Hyde Park",
      value: 5,
      id: 5802,
      isCycle: false,
    },
    {
      source: "Paris",
      target: "Berlin",
      value: 7,
      id: 5900,
      isCycle: false,
    },
    {
      source: "Paris",
      target: "Parc de la Villette",
      value: 5,
      id: 5901,
      isCycle: false,
    },
    {
      source: "Paris",
      target: "Tour Eiffel",
      value: 7,
      id: 5902,
      isCycle: false,
    },
    {
      source: "Paris",
      target: "Arc de Triomphe",
      value: 7,
      id: 5903,
      isCycle: false,
    },
    {
      source: "Namsan",
      target: "Tempelhof Park",
      value: 7,
      id: 6000,
      isCycle: false,
    },
    {
      source: "Namsan",
      target: "Parc de la Villette",
      value: 5,
      id: 6001,
      isCycle: false,
    },
    {
      source: "Namsan",
      target: "Green Park",
      value: 5,
      id: 6002,
      isCycle: false,
    },
    {
      source: "Namsan",
      target: "Hyde Park",
      value: 5,
      id: 6003,
      isCycle: false,
    },
    {
      source: "Memorial to the Murdered Jews of Europe",
      target: "Illogic Inherent in Logic",
      value: 5,
      id: 6100,
      isCycle: false,
    },
    {
      source: "Memorial to the Murdered Jews of Europe",
      target: "Nazi Germany",
      value: 7,
      id: 6101,
      isCycle: false,
    },
    {
      source: "Arc de Triomphe",
      target: "Tour Eiffel",
      value: 10,
      id: 6200,
      isCycle: false,
    },
    {
      source: "Arc de Triomphe",
      target: "Landmark",
      value: 10,
      id: 6201,
      isCycle: false,
    },
    {
      source: "Arc de Triomphe",
      target: "Tempelhof Airport",
      value: 16,
      id: 6202,
      isCycle: false,
    },
    {
      source: "Arc de Triomphe",
      target: "Memorial to the Murdered Jews of Europe",
      value: 7,
      id: 6203,
      isCycle: false,
    },
    {
      source: "Neoliberalism",
      target: "Postmodernity",
      value: 4,
      id: 6300,
      isCycle: false,
    },
    {
      source: "Neoliberalism",
      target: "Efficiency",
      value: 4,
      id: 6301,
      isCycle: false,
    },
    {
      source: "Speech",
      target: "Ich bin ein Berliner",
      value: 4,
      id: 6400,
      isCycle: false,
    },
    {
      source: "Speech",
      target: "Tear Down This Wall",
      value: 4,
      id: 6401,
      isCycle: false,
    },
    {
      source: "Tempelhof Park",
      target: "Tempelhof Airport",
      value: 16,
      id: 6500,
      isCycle: false,
    },
    {
      source: "Illogic Inherent in Logic",
      target: "Illogically Logical",
      value: 7,
      id: 6600,
      isCycle: false,
    },
    {
      source: "Illogic Inherent in Logic",
      target: "Postmodernity",
      value: 5,
      id: 6601,
      isCycle: false,
    },
    {
      source: "Brandenburg Gate",
      target: "Berlin Wall",
      value: 7,
      id: 6700,
      isCycle: false,
    },
    {
      source: "Brandenburg Gate",
      target: "Ich bin ein Berliner",
      value: 5,
      id: 6701,
      isCycle: false,
    },
    {
      source: "Brandenburg Gate",
      target: "Germania Berlin",
      value: 7,
      id: 6702,
      isCycle: false,
    },
    {
      source: "Ronald Reagan",
      target: "Tear Down This Wall",
      value: 4,
      id: 6800,
      isCycle: false,
    },
    {
      source: "Ronald Reagan",
      target: "Neoliberalism",
      value: 3,
      id: 6801,
      isCycle: false,
    },
    {
      source: "Berlin Wall",
      target: "Brandenburg Gate",
      value: 7,
      id: 6900,
      isCycle: false,
    },
    {
      source: "Berlin Wall",
      target: "Tempelhof Airport",
      value: 16,
      id: 6901,
      isCycle: false,
    },
    {
      source: "Berlin Wall",
      target: "Tear Down This Wall",
      value: 7,
      id: 6902,
      isCycle: false,
    },
    {
      source: "Tear Down This Wall",
      target: "Berlin Wall",
      value: 7,
      id: 7000,
      isCycle: false,
    },
    {
      source: "Tear Down This Wall",
      target: "Brandenburg Gate",
      value: 5,
      id: 7001,
      isCycle: false,
    },
    {
      source: "Tear Down This Wall",
      target: "Ronald Reagan",
      value: 4,
      id: 7002,
      isCycle: false,
    },
    {
      source: "Tear Down This Wall",
      target: "Speech",
      value: 4,
      id: 7003,
      isCycle: false,
    },
    {
      source: "Ich bin ein Berliner",
      target: "Berlin Wall",
      value: 7,
      id: 7100,
      isCycle: false,
    },
    {
      source: "Ich bin ein Berliner",
      target: "Brandenburg Gate",
      value: 5,
      id: 7101,
      isCycle: false,
    },
    {
      source: "Ich bin ein Berliner",
      target: "John F. Kennedy",
      value: 4,
      id: 7102,
      isCycle: false,
    },
    {
      source: "Ich bin ein Berliner",
      target: "Speech",
      value: 4,
      id: 7103,
      isCycle: false,
    },
    {
      source: "Peace of our time",
      target: "Munich Agreement",
      value: 3,
      id: 7200,
      isCycle: false,
    },
    {
      source: "Peace of our time",
      target: "War and Peace",
      value: 4,
      id: 7201,
      isCycle: false,
    },
    {
      source: "Peace",
      target: "Peace of our time",
      value: 3,
      id: 7300,
      isCycle: false,
    },
    {
      source: "Peace",
      target: "Peace Treaty",
      value: 2,
      id: 7301,
      isCycle: false,
    },
    {
      source: "Chamberlain",
      target: "World War II",
      value: 7,
      id: 7400,
      isCycle: false,
    },
    {
      source: "Chamberlain",
      target: "Appeasement",
      value: 5,
      id: 7401,
      isCycle: false,
    },
    {
      source: "White Noise",
      target: "Peace",
      value: 3,
      id: 7500,
      isCycle: false,
    },
    {
      source: "White Noise",
      target: "Torture",
      value: 4,
      id: 7501,
      isCycle: false,
    },
    {
      source: "Appeasement",
      target: "World War II",
      value: 7,
      id: 7600,
      isCycle: false,
    },
    {
      source: "Appeasement",
      target: "Nazi Germany",
      value: 7,
      id: 7601,
      isCycle: false,
    },
    {
      source: "Appeasement",
      target: "Chamberlain",
      value: 5,
      id: 7602,
      isCycle: false,
    },
    {
      source: "Munich Agreement",
      target: "Chamberlain",
      value: 4,
      id: 7700,
      isCycle: false,
    },
    {
      source: "Munich Agreement",
      target: "Hitler",
      value: 4,
      id: 7701,
      isCycle: false,
    },
    {
      source: "Germania Berlin",
      target: "Tempelhof Airport",
      value: 16,
      id: 7800,
      isCycle: false,
    },
    {
      source: "War and Peace",
      target: "World War II",
      value: 7,
      id: 7900,
      isCycle: false,
    },
    {
      source: "War and Peace",
      target: "Tolstoy",
      value: 2,
      id: 7901,
      isCycle: false,
    },
    {
      source: "Hitler",
      target: "Nazi Germany",
      value: 7,
      id: 8000,
      isCycle: false,
    },
    {
      source: "Hitler",
      target: "Germania Berlin",
      value: 7,
      id: 8001,
      isCycle: false,
    },
    {
      source: "Totalitarianism",
      target: "Nazi Germany",
      value: 7,
      id: 8100,
      isCycle: false,
    },
    {
      source: "Totalitarianism",
      target: "Soviet Union",
      value: 4,
      id: 8101,
      isCycle: false,
    },
    {
      source: "Dostoyevsky",
      target: "Notes from Underground",
      value: 2,
      id: 8200,
      isCycle: false,
    },
    {
      source: "1984",
      target: "Totalitarianism",
      value: 4,
      id: 8300,
      isCycle: false,
    },
    {
      source: "Notes from Underground",
      target: "2 X 2 = 5",
      value: 3,
      id: 8400,
      isCycle: false,
    },
    {
      source: "2 X 2 = 5",
      target: "2 + 1 ≠ 3",
      value: 4,
      id: 8500,
      isCycle: false,
    },
    {
      source: "2 X 2 = 5",
      target: "1984",
      value: 3,
      id: 8501,
      isCycle: false,
    },
    {
      source: "Tolstoy",
      target: "Dostoyevsky",
      value: 2,
      id: 8600,
      isCycle: false,
    },
    {
      source: "Soviet Union",
      target: "Cold War",
      value: 4,
      id: 8700,
      isCycle: false,
    },
    {
      source: "Peace Treaty",
      target: "Treaty of Versailles",
      value: 3,
      id: 8800,
      isCycle: false,
    },
    {
      source: "Treaty of Versailles",
      target: "World War I",
      value: 4,
      id: 8900,
      isCycle: false,
    },
    {
      source: "Treaty of Versailles",
      target: "German Hyperinflation",
      value: 4,
      id: 8901,
      isCycle: false,
    },
    {
      source: "Treaty of Versailles",
      target: "Compiegne Wagon",
      value: 4,
      id: 8902,
      isCycle: false,
    },
    {
      source: "Compiegne Wagon",
      target: "Hitler",
      value: 5,
      id: 9000,
      isCycle: false,
    },
    {
      source: "Compiegne Wagon",
      target: "Propaganda",
      value: 7,
      id: 9001,
      isCycle: false,
    },
    {
      source: "Inequality",
      target: "Nonequality",
      value: 7,
      id: 9100,
      isCycle: false,
    },
    {
      source: "Propaganda",
      target: "Tempelhof Airport",
      value: 16,
      id: 9200,
      isCycle: false,
    },
    {
      source: "Propaganda",
      target: "Brandenburg Gate",
      value: 7,
      id: 9201,
      isCycle: false,
    },
    {
      source: "Propaganda",
      target: "Crowd Psychology",
      value: 7,
      id: 9202,
      isCycle: false,
    },
    {
      source: "Propaganda",
      target: "Nazi Germany",
      value: 10,
      id: 9203,
      isCycle: false,
    },
    {
      source: "World War I",
      target: "German Hyperinflation",
      value: 5,
      id: 9300,
      isCycle: false,
    },
    {
      source: "World War I",
      target: "World War II",
      value: 7,
      id: 9301,
      isCycle: false,
    },
    {
      source: "Nonequilibrium",
      target: "Entropy",
      value: 3,
      id: 9400,
      isCycle: false,
    },
    {
      source: "Nonequilibrium",
      target: "2 X 2 = 5",
      value: 3,
      id: 9401,
      isCycle: false,
    },
    {
      source: "Nonlinear",
      target: "The Butterfly Effect",
      value: 5,
      id: 9500,
      isCycle: false,
    },
    {
      source: "Nonlinear",
      target: "Illogically Logical",
      value: 7,
      id: 9501,
      isCycle: false,
    },
    {
      source: "World is not equal",
      target: "Berlin Nonequality",
      value: 16,
      id: 9600,
      isCycle: false,
    },
    {
      source: "World is not equal",
      target: "Nonequilibrium",
      value: 4,
      id: 9601,
      isCycle: false,
    },
    {
      source: "Entropy",
      target: "Nonlinear",
      value: 4,
      id: 9700,
      isCycle: false,
    },
    {
      source: "German Hyperinflation",
      target: "Nazi Germany",
      value: 7,
      id: 9800,
      isCycle: false,
    },
    {
      source: "German Hyperinflation",
      target: "Inequality",
      value: 5,
      id: 9801,
      isCycle: false,
    },
    {
      source: "The Butterfly Effect",
      target: "Illogically Logical",
      value: 7,
      id: 9900,
      isCycle: false,
    },
    {
      source: "Torture",
      target: "World War II",
      value: 7,
      id: 10000,
      isCycle: false,
    },
    {
      source: "Torture",
      target: "Cold War",
      value: 5,
      id: 10001,
      isCycle: false,
    },
    {
      source: "Cold War",
      target: "Berlin Blockade",
      value: 7,
      id: 10100,
      isCycle: false,
    },
    {
      source: "Cold War",
      target: "Berlin Wall",
      value: 7,
      id: 10101,
      isCycle: false,
    },
    {
      source: "Cold War",
      target: "Korean War",
      value: 5,
      id: 10102,
      isCycle: false,
    },
    {
      source: "Pablo Picasso",
      target: "Cubism",
      value: 2,
      id: 10200,
      isCycle: false,
    },
    {
      source: "Pablo Picasso",
      target: "Modernism",
      value: 3,
      id: 10201,
      isCycle: false,
    },
    {
      source: "Modernism",
      target: "Modern Logics",
      value: 3,
      id: 10300,
      isCycle: false,
    },
    {
      source: "Modernism",
      target: "Postmodernism",
      value: 4,
      id: 10301,
      isCycle: false,
    },
    {
      source: "Korean War",
      target: "Pablo Picasso",
      value: 3,
      id: 10400,
      isCycle: false,
    },
    {
      source: "Korean War",
      target: "World War II",
      value: 7,
      id: 10401,
      isCycle: false,
    },
    {
      source: "Dadaism",
      target: "Postmodernism",
      value: 4,
      id: 10500,
      isCycle: false,
    },
    {
      source: "Dadaism",
      target: "Modern Logics",
      value: 3,
      id: 10501,
      isCycle: false,
    },
    {
      source: "Postmodernism",
      target: "Useless is Useful",
      value: 7,
      id: 10600,
      isCycle: false,
    },
    {
      source: "Postmodernism",
      target: "Limitation of Logic",
      value: 5,
      id: 10601,
      isCycle: false,
    },
    {
      source: "Postmodernism",
      target: "Postmodernity",
      value: 5,
      id: 10602,
      isCycle: false,
    },
    {
      source: "Limitation of Logic",
      target: "Postmodernity",
      value: 5,
      id: 10700,
      isCycle: false,
    },
    {
      source: "Limitation of Logic",
      target: "Illogically Logical",
      value: 7,
      id: 10701,
      isCycle: false,
    },
    {
      source: "Cubism",
      target: "Modernism",
      value: 3,
      id: 10800,
      isCycle: false,
    },
    {
      source: "Cubism",
      target: "Dadaism",
      value: 3,
      id: 10801,
      isCycle: false,
    },
    {
      source: "Berlin Blockade",
      target: "Tempelhof Airport",
      value: 16,
      id: 10900,
      isCycle: false,
    },
    {
      source: "Berlin Blockade",
      target: "Berlin Airlift",
      value: 10,
      id: 10901,
      isCycle: false,
    },
    {
      source: "Berlin Blockade",
      target: "Berlin Wall",
      value: 10,
      id: 10902,
      isCycle: false,
    },
    {
      source: "Berlin Airlift",
      target: "Tempelhof Airport",
      value: 16,
      id: 11000,
      isCycle: false,
    },
    {
      source: "Gravity",
      target: "Newtonian Physics",
      value: 2,
      id: 11100,
      isCycle: false,
    },
    {
      source: "Gravity",
      target: "The Use of Gravity",
      value: 2,
      id: 11101,
      isCycle: false,
    },
    {
      source: "Newtonian Physics",
      target: "Modern Logics",
      value: 3,
      id: 11200,
      isCycle: false,
    },
    {
      source: "Invention of Airplane",
      target: "Runway",
      value: 7,
      id: 11300,
      isCycle: false,
    },
    {
      source: "Invention of Airplane",
      target: "Atomic Bomb",
      value: 5,
      id: 11301,
      isCycle: false,
    },
    {
      source: "Industrial Revolution",
      target: "Modern Logics",
      value: 3,
      id: 11400,
      isCycle: false,
    },
    {
      source: "Going Against Gravity",
      target: "Going Beyond Gravity",
      value: 3,
      id: 11500,
      isCycle: false,
    },
    {
      source: "Going Against Gravity",
      target: "Invention of Airplane",
      value: 4,
      id: 11501,
      isCycle: false,
    },
    {
      source: "The Use of Gravity",
      target: "Industrial Revolution",
      value: 2,
      id: 11600,
      isCycle: false,
    },
    {
      source: "The Use of Gravity",
      target: "Going Against Gravity",
      value: 3,
      id: 11601,
      isCycle: false,
    },
    {
      source: "Atomic Bomb",
      target: "World War II",
      value: 7,
      id: 11700,
      isCycle: false,
    },
    {
      source: "Atomic Bomb",
      target: "Postmodernity",
      value: 5,
      id: 11701,
      isCycle: false,
    },
    {
      source: "Atomic Bomb",
      target: "Illogic Inherent in Logic",
      value: 5,
      id: 11702,
      isCycle: false,
    },
    {
      source: "Postmodernity",
      target: "World War II",
      value: 7,
      id: 11800,
      isCycle: false,
    },
    {
      source: "Postmodernity",
      target: "Useless is Useful",
      value: 7,
      id: 11801,
      isCycle: false,
    },
    {
      source: "Postmodernity",
      target: "Postmodernism",
      value: 5,
      id: 11802,
      isCycle: false,
    },
    {
      source: "Quantum Physics",
      target: "Atomic Bomb",
      value: 4,
      id: 11900,
      isCycle: false,
    },
    {
      source: "Quantum Physics",
      target: "Postmodernity",
      value: 4,
      id: 11901,
      isCycle: false,
    },
    {
      source: "Modern Logics",
      target: "Postmodernity",
      value: 4,
      id: 12000,
      isCycle: false,
    },
    {
      source: "Modern Logics",
      target: "2 + 1 = 3",
      value: 4,
      id: 12001,
      isCycle: false,
    },
    {
      source: "Going Beyond Gravity",
      target: "Theory of Relativity",
      value: 3,
      id: 12100,
      isCycle: false,
    },
    {
      source: "Theory of Relativity",
      target: "Atomic Bomb",
      value: 4,
      id: 12200,
      isCycle: false,
    },
    {
      source: "Theory of Relativity",
      target: "Quantum Physics",
      value: 3,
      id: 12201,
      isCycle: false,
    },
    {
      source: "Runway",
      target: "Building Third Runway",
      value: 16,
      id: 12300,
      isCycle: false,
    },
    {
      source: "Runway",
      target: "Building Unusable Runway",
      value: 10,
      id: 12301,
      isCycle: false,
    },
    {
      source: "Useless is Useful",
      target: "Building Third Runway",
      value: 16,
      id: 12400,
      isCycle: false,
    },
    {
      source: "Useless is Useful",
      target: "Building Unusable Runway",
      value: 10,
      id: 12401,
      isCycle: false,
    },
    {
      source: "World War II",
      target: "Nazi Germany",
      value: 10,
      id: 12500,
      isCycle: false,
    },
    {
      source: "World War II",
      target: "Tempelhof Airport",
      value: 16,
      id: 12501,
      isCycle: false,
    },
    {
      source: "World War II",
      target: "Postmodernity",
      value: 7,
      id: 12502,
      isCycle: false,
    },
    {
      source: "World War II",
      target: "Cold War",
      value: 7,
      id: 12503,
      isCycle: false,
    },
    {
      source: "World War II",
      target: "Hitler",
      value: 7,
      id: 12504,
      isCycle: false,
    },
    {
      source: "World War II",
      target: "Soviet Union",
      value: 5,
      id: 12505,
      isCycle: false,
    },
    {
      source: "Nazi Germany",
      target: "Tempelhof Airport",
      value: 16,
      id: 12600,
      isCycle: false,
    },
    {
      source: "Nazi Germany",
      target: "Hitler",
      value: 7,
      id: 12601,
      isCycle: false,
    },
    {
      source: "Nazi Germany",
      target: "Holocaust",
      value: 7,
      id: 12602,
      isCycle: false,
    },
    {
      source: "Nazi Germany",
      target: "World War II",
      value: 10,
      id: 12603,
      isCycle: false,
    },
    {
      source: "Nazi Germany",
      target: "Germania Berlin",
      value: 10,
      id: 12604,
      isCycle: false,
    },
    {
      source: "Nazi Germany",
      target: "Propaganda",
      value: 10,
      id: 12605,
      isCycle: false,
    },
    {
      source: "Nazi Germany",
      target: "Illogically Logical",
      value: 10,
      id: 12606,
      isCycle: false,
    },
    {
      source: "Nazi Germany",
      target: "Logically Illogical",
      value: 7,
      id: 12607,
      isCycle: false,
    },
    {
      source: "Nazi Germany",
      target: "Illogic Inherent in Logic",
      value: 7,
      id: 12608,
      isCycle: false,
    },
    {
      source: "Holocaust",
      target: "Nazi Germany",
      value: 7,
      id: 12700,
      isCycle: false,
    },
    {
      source: "Holocaust",
      target: "Memorial to the Murdered Jews of Europe",
      value: 5,
      id: 12701,
      isCycle: false,
    },
    {
      source: "Holocaust",
      target: "Illogic Inherent in Logic",
      value: 5,
      id: 12702,
      isCycle: false,
    },
    {
      source: "Holocaust",
      target: "Notes from Underground",
      value: 3,
      id: 12703,
      isCycle: false,
    },
    {
      source: "Tempelhof Airport",
      target: "Building Third Runway",
      value: 50,
      id: 12800,
      isCycle: true,
    },
    {
      source: "Building Third Runway",
      target: "Berlin Nonequality",
      value: 50,
      id: 12900,
      isCycle: true,
    },
    {
      source: "Berlin Nonequality",
      target: "≠",
      value: 50,
      id: 13000,
      isCycle: true,
    },
    {
      source: "≠",
      target: "Not Equal",
      value: 50,
      id: 13100,
      isCycle: true,
    },
    {
      source: "Not Equal",
      target: "Tempelhof Airport",
      value: 50,
      id: 13200,
      isCycle: true,
    },
  ],
};
