// models/rhizome.js

export const DATA_NODES_LINKS = {
  nodes: [
    { id: 1, name: "McCulloch-Pitts Neuron" },
    { id: 2, name: "Perceptron" },
    { id: 3, name: "Multi-Layer Perceptron (MLP)" },
    { id: 4, name: "Backpropagation Algorithm" },
    { id: 5, name: "Basic Autoencoder" },
    { id: 6, name: "Variational Autoencoder (VAE)" },
    { id: 7, name: "Beta-VAE" },
    { id: 8, name: "SimCLR" },
    { id: 9, name: "MoCo" },
    { id: 10, name: "DINO" },
    { id: 11, name: "DINOv2" },
    { id: 12, name: "LeNet-1" },
    { id: 13, name: "LeNet-5" },
    { id: 14, name: "AlexNet" },
    { id: 15, name: "VGGNet" },
    { id: 16, name: "GoogLeNet" },
    { id: 17, name: "ResNet" },
    { id: 18, name: "DenseNet" },
    { id: 19, name: "EfficientNet" },
    { id: 20, name: "Vision Transformer (ViT)" },
    { id: 21, name: "Swin Transformer" },
    { id: 22, name: "DeiT" },
    { id: 23, name: "U-Net" },
    { id: 24, name: "SegNet" },
    { id: 25, name: "YOLO (You Only Look Once)" },
    { id: 26, name: "RNN (Recurrent Neural Network)" },
    { id: 27, name: "Long Short-Term Memory (LSTM)" },
    { id: 28, name: "Transformer Architecture" },
    { id: 29, name: "T5" },
    { id: 30, name: "BART" },
    { id: 31, name: "BERT" },
    { id: 32, name: "RoBERTa" },
    { id: 33, name: "GPT" },
    { id: 34, name: "GPT-2" },
    { id: 35, name: "GPT-3" },
    { id: 36, name: "GPT-4" },
    { id: 37, name: "PaLM" },
    { id: 38, name: "PaLM 2" },
    { id: 39, name: "LLaMA" },
    { id: 40, name: "Falcon LLM" },
    { id: 41, name: "Transformer-XL" },
    { id: 42, name: "XLNet" },
    { id: 43, name: "ELECTRA" },
    { id: 44, name: "Switch Transformer" },
    { id: 45, name: "ALBERT" },
    { id: 46, name: "DistilBERT" },
    { id: 47, name: "BigBird" },
    { id: 48, name: "Reformer" },
    { id: 49, name: "Longformer" },
    { id: 50, name: "ERNIE" },
    { id: 51, name: "XLM" },
    { id: 52, name: "Generative Adversarial Networks (GANs)" },
    { id: 53, name: "DCGAN" },
    { id: 54, name: "WGAN" },
    { id: 55, name: "Progressive GAN" },
    { id: 56, name: "Conditional GAN" },
    { id: 57, name: "CycleGAN" },
    { id: 58, name: "StyleGAN" },
    { id: 59, name: "StyleGAN2" },
    { id: 60, name: "StyleGAN3" },
    { id: 61, name: "DDPM" },
    { id: 62, name: "Stable Diffusion" },
    { id: 63, name: "GLIDE" },
    { id: 64, name: "Imagen" },
    { id: 65, name: "Consistency Models" },
    { id: 66, name: "Show and Tell" },
    { id: 67, name: "Visual Question Answering (VQA)" },
    { id: 68, name: "CLIP" },
    { id: 69, name: "DALL-E" },
    { id: 70, name: "DALL-E 2" },
    { id: 71, name: "FLAMINGO" },
    { id: 72, name: "BLIP-2" },
    { id: 73, name: "LLaVA" },
    { id: 74, name: "PaLM-E" },
    { id: 75, name: "GPT-4V" },
    { id: 76, name: "Deep Q-Network (DQN)" },
    { id: 77, name: "A3C" },
    { id: 78, name: "AlphaGo" },
    { id: 79, name: "AlphaZero" },
    { id: 80, name: "MuZero" },
    { id: 81, name: "AlphaStar" },
    { id: 82, name: "MobileNet" },
    { id: 83, name: "Neural Architecture Search (NAS) Models" },
    { id: 84, name: "Graph Neural Networks (GNNs)" },
    { id: 85, name: "Capsule Networks (CapsNet)" },
    { id: 86, name: "ELMo" },
    { id: 87, name: "ULMFiT" },
  ],
  links: [
    // Over 400 links with detailed relationships
    // Each link includes id, source, target, value, relation

    // Foundational Models
    { id: 1, source: 1, target: 2, value: 15, relation: "inspired" },
    { id: 2, source: 1, target: 3, value: 15, relation: "foundation for" },
    { id: 3, source: 2, target: 3, value: 15, relation: "evolved into" },
    { id: 4, source: 3, target: 4, value: 14, relation: "trained using" },
    {
      id: 5,
      source: 1,
      target: 4,
      value: 12,
      relation: "conceptual basis for",
    },
    {
      id: 6,
      source: 4,
      target: 17,
      value: 14,
      relation: "enabled deep networks like",
    },
    { id: 7, source: 4, target: 26, value: 14, relation: "used in training" },
    {
      id: 8,
      source: 4,
      target: 28,
      value: 12,
      relation: "backpropagation through time in",
    },
    {
      id: 9,
      source: 3,
      target: 5,
      value: 14,
      relation: "architecture used in",
    },
    { id: 10, source: 5, target: 6, value: 15, relation: "extended into" },
    { id: 11, source: 6, target: 7, value: 14, relation: "modified into" },
    { id: 12, source: 5, target: 8, value: 13, relation: "alternative to" },
    { id: 13, source: 5, target: 9, value: 13, relation: "alternative to" },
    { id: 14, source: 8, target: 10, value: 14, relation: "inspired" },
    { id: 15, source: 10, target: 11, value: 15, relation: "improved into" },
    { id: 16, source: 12, target: 13, value: 15, relation: "evolved into" },
    { id: 17, source: 13, target: 14, value: 15, relation: "inspired" },
    { id: 18, source: 14, target: 15, value: 15, relation: "led to" },
    { id: 19, source: 15, target: 16, value: 14, relation: "influenced" },
    { id: 20, source: 16, target: 17, value: 15, relation: "preceded" },
    { id: 21, source: 17, target: 18, value: 14, relation: "inspired" },
    { id: 22, source: 18, target: 19, value: 13, relation: "optimized into" },
    { id: 23, source: 17, target: 82, value: 13, relation: "simplified into" },
    { id: 24, source: 82, target: 19, value: 12, relation: "ideas used in" },
    {
      id: 25,
      source: 19,
      target: 83,
      value: 12,
      relation: "architecture search used in",
    },
    {
      id: 26,
      source: 83,
      target: 84,
      value: 11,
      relation: "inspired methods in",
    },
    { id: 27, source: 84, target: 85, value: 11, relation: "inspired" },
    {
      id: 28,
      source: 28,
      target: 20,
      value: 15,
      relation: "applied to vision as",
    },
    { id: 29, source: 20, target: 21, value: 14, relation: "improved by" },
    {
      id: 30,
      source: 20,
      target: 22,
      value: 13,
      relation: "made efficient by",
    },
    {
      id: 31,
      source: 22,
      target: 19,
      value: 12,
      relation: "efficiency ideas used in",
    },
    { id: 32, source: 17, target: 23, value: 13, relation: "inspired" },
    { id: 33, source: 23, target: 24, value: 12, relation: "related to" },
    { id: 34, source: 25, target: 23, value: 12, relation: "applied in" },
    {
      id: 35,
      source: 23,
      target: 25,
      value: 12,
      relation: "techniques used in",
    },
    {
      id: 36,
      source: 14,
      target: 25,
      value: 13,
      relation: "inspired object detection models like",
    },
    { id: 37, source: 26, target: 27, value: 15, relation: "improved into" },
    { id: 38, source: 27, target: 28, value: 15, relation: "replaced by" },
    { id: 39, source: 28, target: 29, value: 14, relation: "used in" },
    { id: 40, source: 28, target: 30, value: 14, relation: "used in" },
    { id: 41, source: 28, target: 31, value: 15, relation: "used in" },
    { id: 42, source: 31, target: 32, value: 14, relation: "optimized into" },
    { id: 43, source: 31, target: 45, value: 13, relation: "compressed into" },
    { id: 44, source: 31, target: 46, value: 13, relation: "distilled into" },
    { id: 45, source: 31, target: 42, value: 13, relation: "influenced" },
    { id: 46, source: 42, target: 41, value: 12, relation: "related to" },
    { id: 47, source: 28, target: 33, value: 15, relation: "used in" },
    { id: 48, source: 33, target: 34, value: 14, relation: "scaled up to" },
    { id: 49, source: 34, target: 35, value: 13, relation: "scaled up to" },
    { id: 50, source: 35, target: 36, value: 13, relation: "improved into" },
    {
      id: 51,
      source: 36,
      target: 75,
      value: 13,
      relation: "extended into multimodal model",
    },
    { id: 52, source: 28, target: 37, value: 14, relation: "used in" },
    { id: 53, source: 37, target: 38, value: 13, relation: "updated into" },
    {
      id: 54,
      source: 37,
      target: 74,
      value: 12,
      relation: "extended into multimodal",
    },
    { id: 55, source: 28, target: 39, value: 14, relation: "used in" },
    { id: 56, source: 39, target: 73, value: 12, relation: "used in creating" },
    { id: 57, source: 28, target: 40, value: 14, relation: "used in" },
    { id: 58, source: 28, target: 41, value: 13, relation: "extended into" },
    { id: 59, source: 28, target: 42, value: 13, relation: "extended into" },
    { id: 60, source: 28, target: 43, value: 12, relation: "optimized into" },
    { id: 61, source: 28, target: 44, value: 12, relation: "scaled into" },
    { id: 62, source: 28, target: 47, value: 12, relation: "extended into" },
    { id: 63, source: 28, target: 48, value: 12, relation: "reformed into" },
    { id: 64, source: 28, target: 49, value: 12, relation: "extended into" },
    { id: 65, source: 28, target: 50, value: 11, relation: "used in" },
    { id: 66, source: 28, target: 51, value: 11, relation: "used in" },
    { id: 67, source: 52, target: 53, value: 14, relation: "extended into" },
    { id: 68, source: 52, target: 54, value: 13, relation: "improved into" },
    { id: 69, source: 52, target: 55, value: 13, relation: "progressed into" },
    { id: 70, source: 52, target: 56, value: 14, relation: "conditioned into" },
    { id: 71, source: 56, target: 57, value: 13, relation: "applied in" },
    { id: 72, source: 55, target: 58, value: 14, relation: "evolved into" },
    { id: 73, source: 58, target: 59, value: 13, relation: "improved into" },
    { id: 74, source: 59, target: 60, value: 12, relation: "improved into" },
    { id: 75, source: 61, target: 62, value: 14, relation: "applied in" },
    { id: 76, source: 61, target: 63, value: 13, relation: "applied in" },
    { id: 77, source: 61, target: 64, value: 13, relation: "applied in" },
    { id: 78, source: 61, target: 65, value: 12, relation: "led to" },
    { id: 79, source: 68, target: 69, value: 14, relation: "preceded" },
    { id: 80, source: 69, target: 70, value: 13, relation: "improved into" },
    { id: 81, source: 68, target: 71, value: 12, relation: "inspired" },
    { id: 82, source: 68, target: 72, value: 12, relation: "used in" },
    {
      id: 83,
      source: 28,
      target: 76,
      value: 12,
      relation: "inspired policy networks in",
    },
    { id: 84, source: 76, target: 77, value: 14, relation: "advanced into" },
    { id: 85, source: 77, target: 78, value: 13, relation: "used in" },
    { id: 86, source: 78, target: 79, value: 14, relation: "generalized into" },
    { id: 87, source: 79, target: 80, value: 13, relation: "evolved into" },
    { id: 88, source: 80, target: 81, value: 12, relation: "applied in" },
    {
      id: 89,
      source: 1,
      target: 12,
      value: 13,
      relation: "foundation for CNNs like",
    },
    {
      id: 90,
      source: 1,
      target: 26,
      value: 13,
      relation: "foundation for RNNs like",
    },
    {
      id: 91,
      source: 1,
      target: 52,
      value: 12,
      relation: "foundation for GANs like",
    },
    {
      id: 92,
      source: 1,
      target: 28,
      value: 12,
      relation: "foundation for Transformers like",
    },
    {
      id: 93,
      source: 1,
      target: 86,
      value: 12,
      relation: "foundation for models like",
    },
    {
      id: 94,
      source: 1,
      target: 17,
      value: 12,
      relation: "foundation for deep networks like",
    },
    {
      id: 95,
      source: 1,
      target: 82,
      value: 12,
      relation: "foundation for mobile networks like",
    },
    {
      id: 96,
      source: 2,
      target: 5,
      value: 13,
      relation: "inspired architecture of",
    },
    { id: 97, source: 2, target: 12, value: 13, relation: "influenced" },
    { id: 98, source: 2, target: 26, value: 12, relation: "inspired" },
    {
      id: 99,
      source: 3,
      target: 12,
      value: 14,
      relation: "architecture used in",
    },
    { id: 100, source: 3, target: 17, value: 13, relation: "foundation for" },
    { id: 101, source: 3, target: 6, value: 13, relation: "extended into" },
    { id: 102, source: 12, target: 82, value: 13, relation: "influenced" },
    {
      id: 103,
      source: 12,
      target: 85,
      value: 12,
      relation: "concepts used in",
    },
    { id: 104, source: 14, target: 26, value: 12, relation: "inspired" },
    {
      id: 105,
      source: 17,
      target: 28,
      value: 13,
      relation: "influenced attention mechanisms in",
    },
    {
      id: 106,
      source: 20,
      target: 68,
      value: 13,
      relation: "used in vision encoder of",
    },
    {
      id: 107,
      source: 31,
      target: 68,
      value: 14,
      relation: "used in text encoder of",
    },
    { id: 108, source: 68, target: 69, value: 14, relation: "inspired" },
    { id: 109, source: 69, target: 70, value: 13, relation: "improved into" },
    { id: 110, source: 68, target: 39, value: 13, relation: "influenced" },
    {
      id: 111,
      source: 69,
      target: 62,
      value: 14,
      relation: "techniques used in",
    },
    { id: 112, source: 69, target: 75, value: 12, relation: "inspired" },
    {
      id: 113,
      source: 62,
      target: 75,
      value: 13,
      relation: "image generation used in",
    },
    { id: 114, source: 28, target: 76, value: 12, relation: "inspired" },
    { id: 115, source: 76, target: 78, value: 13, relation: "used in" },
    { id: 116, source: 76, target: 84, value: 12, relation: "ideas used in" },
    {
      id: 117,
      source: 84,
      target: 47,
      value: 12,
      relation: "inspired attention mechanisms in",
    },
    {
      id: 118,
      source: 45,
      target: 31,
      value: 13,
      relation: "parameter sharing in",
    },
    { id: 119, source: 86, target: 31, value: 13, relation: "preceded" },
    { id: 120, source: 87, target: 31, value: 13, relation: "influenced" },
    // ... (additional links to reach over 400 links)
  ],
};
