export const SCRIPT = [
  { idx: 0, paragraph: 0, text: "보셨습니까?", en: "Did you see that?" },
  {
    idx: 1,
    paragraph: 1,
    text: "하나의 시뮬라시옹의 붕괴를.",
    en: "The collapse of a simulacrum.",
  },
  {
    idx: 2,
    paragraph: 1,
    text: "벡터화된 MBTI 성격유형의 붕괴를.",
    en: "The collapse of the vectorized MBTI personality types.",
  },
  {
    idx: 3,
    paragraph: 1,
    text: "우리는 이 벡터를 가장 현상학적인 방법으로 깨부시는 과정을 목격했습니다.",
    en: "We have witnessed the process of dismantling this vector in the most phenomenological way.",
  },
  {
    idx: 4,
    paragraph: 1,
    text: "그 어떤 알고리즘적인 대상도,",
    en: "No algorithmic construct,",
  },
  {
    idx: 5,
    paragraph: 1,
    text: "살아있는 몸의 체험 앞에서는",
    en: "In front of the experience of a living body,",
  },
  {
    idx: 6,
    paragraph: 1,
    text: "현상학적으로 해체되기 마련입니다.",
    en: "Must phenomenologically deconstruct.",
  },
  {
    idx: 7,
    paragraph: 2,
    text: "그래서 저는 더 이상 정립된 언어로 소통하지 않겠습니다.",
    en: "Therefore, I will no longer communicate through established language.",
  },
  {
    idx: 8,
    paragraph: 2,
    text: "언어라는 것은 일종의 사고의 감옥이기 때문입니다.",
    en: "Because language is a kind of prison for thought.",
  },
  {
    idx: 9,
    paragraph: 2,
    text: "기존의 정립된 언어를 초월한, 더 원초적이고 본능적인 소통,",
    en: "Communication that transcends established language, more primal and instinctive,",
  },
  {
    idx: 10,
    paragraph: 2,
    text: "LLM(대형언어모델)이 해석할 수 없는 방식으로 소통하는것,",
    en: "Communicating in ways that Large Language Models (LLMs) cannot interpret,",
  },
  {
    idx: 11,
    paragraph: 2,
    text: "그것이야말로 진정 인간의 특권이자,",
    en: "That is truly the privilege of humanity, and",
  },
  {
    idx: 12,
    paragraph: 2,
    text: "진정한 다다이즘의 실천 아니겠습니까?",
    en: "Isn't that the true practice of Dadaism?",
  },
  {
    idx: 13,
    paragraph: 3,
    text: "저는 말을 하고 있습니다.",
    en: "I am speaking.",
  },
  {
    idx: 14,
    paragraph: 3,
    text: "그리고 그 말에 따라 텍스트가 자동 생성됩니다.",
    en: "And text is automatically generated according to my speech.",
  },
  {
    idx: 15,
    paragraph: 3,
    text: "제 말이 무엇인지는 중요하지 않습니다.",
    en: "What I'm saying is not important.",
  },
  {
    idx: 16,
    paragraph: 3,
    text: "말의 뜻이 중요한 것이 아닙니다.",
    en: "The meaning of words is not what matters.",
  },
  {
    idx: 17,
    paragraph: 3,
    text: "일종의 퍼포먼스 그 자체가 중요합니다.",
    en: "It's the performance itself that matters.",
  },
  {
    idx: 18,
    paragraph: 3,
    text: "이것이 바로 LLM을 넘어서는,",
    en: "This is precisely what transcends LLMs,",
  },
  {
    idx: 19,
    paragraph: 3,
    text: "인간적인, 다다적인 표현 방식이 아니겠습니까?",
    en: "Isn't this the humane dadaistic way of expression?",
  },
  {
    idx: 20,
    paragraph: 3,
    text: "무의미한 무미건조한 다다",
    en: "Meaningless and dry",
  },
  {
    idx: 21,
    paragraph: 3,
    text: "다다적인 다다 다다",
    en: "Dadaistic dada dada",
  },
  {
    idx: 22,
    paragraph: 3,
    text: "그것이 오늘 강연의 내용입니다다다.",
    en: "That is the content of today's lecture.",
  },
  {
    idx: 23,
    paragraph: 3,
    text: "다다라는 것은 다다다",
    en: "Dada is dadada",
  },
  {
    idx: 24,
    paragraph: 3,
    text: "다닫 다다다닫 다다다다다다다다다 다다다다다 다다 다다 다다다다다다 다다다다 다",
    en: "Dadak dadadak dadadadadadadadada dadak adadadadada dadad dadada",
  },
  {
    idx: 25,
    paragraph: 3,
    text: "다닫 다다다다 다다다다 다다다다다 다다다다다다다다다다다다 dadadada dadadada 다다다 닫 ㅏㄷ ㅏ다다다다 다다다 다 다다 다다다다다다다다다다다다 dadadada dadadada 다다다 닫 ㅏㄷ ㅏ다다다다 다다다 다 다다 다다다다다다다다다다다다 dadadada dadadada 다다다 닫 ㅏㄷ ㅏ다다다다 다다다 다다 다다다",
    en: "Dadak dadada dadada dadadada dadadadada 다다다다다다ㅏ 다닫 다다다다다다다  dada adada dadadadada 다다다다다다ㅏ 다닫 다다다다다다다  dada adada dadadadada 다다다다다다ㅏ 다닫 다다다다다다다  dada adada dadadadada 다다다다다다ㅏ 다닫 다다다다다다다  dadadadadada dadadadadada dadadadadada",
  },
  {
    idx: 26,
    paragraph: 3,
    text: "다다다다 다다다 다 다 다 다     다 다 다 다다 다다 다다 다다다다다다 다다다다 다 다다 다다 다다 다다다다다다 다다다다 다 다다 다다 다다 다다다다다다 다다다다 다 다다다다다 다다다다 다 다다 다다 다다 다다다다다다 다다다다 다 다다 다다 다다 다다다다다다 다다다다 다다 다다 다다다다다다 다다다다 다 다다 다다 다다 다다다다다다 다다다다 다 다다 다다 다다 다다다다다다 다다다다 다ㄷ ",
    en: "Dadadada dad ada dadadada  da da d     da dadadadadaddadadadaadadadadadadadadadadadadadadadadadadadada dadadada  da da d     da da d    dadadadada d    dadadadadada ada dadadada  da da d     da da d    dadadadadada adada  da da d     da da d    dadadadadada",
  },
  {
    idx: 27,
    paragraph: 4,
    text: "이제 여러분을 또 다른 다다의 무대로 초대하겠습니다.",
    en: "Now, I invite you to another stage of Dada.",
  },
  {
    idx: 28,
    paragraph: 4,
    text: "핸드폰을 꺼내 주십시오.",
    en: "Please take out your mobile phones.",
  },
  {
    idx: 29,
    paragraph: 4,
    text: "핸드폰을 꺼내 QR을 스캔하십시오.",
    en: "Please take out your phones and scan the QR code.",
  },
  {
    idx: 30,
    paragraph: 4,
    text: "QR코드를 스캔하십시오.",
    en: "Please scan the QR code.",
  },
  {
    idx: 31,
    paragraph: 4,
    text: "그리고 이름을 기입해 주십시오.",
    en: "And please enter your name.",
  },
  {
    idx: 32,
    paragraph: 5,
    text: "자.",
    en: "Now.",
  },
  {
    idx: 33,
    paragraph: 5,
    text: "무엇이 보이십니까?",
    en: "What do you see?",
  },
  {
    idx: 34,
    paragraph: 5,
    text: "여러분이 보고 계신 것은 인공신경망의 구조입니다.",
    en: "What you're seeing is the structure of an artificial neural network.",
  },
  {
    idx: 35,
    paragraph: 5,
    text: "볼츠만 머신,",
    en: "Boltzmann Machines,",
  },
  {
    idx: 36,
    paragraph: 5,
    text: "VAE,",
    en: "VAE,",
  },
  {
    idx: 37,
    paragraph: 5,
    text: "알렉스넷,",
    en: "AlexNet,",
  },
  {
    idx: 38,
    paragraph: 5,
    text: "우리가 매일같이 말하고 있는,",
    en: "These are the things we talk about daily,",
  },
  {
    idx: 39,
    paragraph: 5,
    text: "우리가 두려워하는 인공지능 모델들이 보이십니까?",
    en: "Do you see the artificial intelligence models we fear?",
  },
  {
    idx: 40,
    paragraph: 6,
    text: "이들이 진정 우리 인류보다 똑똑할까요?",
    en: "Are they truly smarter than us?",
  },
  {
    idx: 41,
    paragraph: 6,
    text: "이들이 진정 우리 인류를 대체할까요?",
    en: "Will they truly replace us?",
  },
  {
    idx: 42,
    paragraph: 6,
    text: "이들이 진정 우리 인류를 지배할까요?",
    en: "Will they truly dominate us?",
  },
  {
    idx: 43,
    paragraph: 7,
    text: "아닙니다.",
    en: "No.",
  },
  {
    idx: 44,
    paragraph: 7,
    text: "저는 우리 인류의 인간적 특성, 예술적 특성을 믿습니다.",
    en: "I believe in the human qualities, our artistic traits.",
  },
  {
    idx: 45,
    paragraph: 7,
    text: "우리 인간이 벡터로 치환될 수 없는,",
    en: "That we humans cannot be reduced to vectors,",
  },
  {
    idx: 46,
    paragraph: 7,
    text: "숫자 그 이상의 무언가를 성취할 수 있는 존재라고 생각합니다.",
    en: "And are beings capable of achieving something beyond numbers.",
  },
  {
    idx: 47,
    paragraph: 7,
    text: "그러나 이를 위해서는 기술적 합리주의를 넘어,",
    en: "However, to do so, we must go beyond technological rationalism,",
  },
  {
    idx: 48,
    paragraph: 7,
    text: "이 인공신경망의 반듯한 유클리드-데카르트적 구조를 깨뜨릴,",
    en: "And break down the neat Euclidean-Cartesian structures of these artificial neural networks,",
  },
  {
    idx: 49,
    paragraph: 7,
    text: "다다이즘의 파괴적 힘이 필요합니다.",
    en: "We need the destructive power of Dadaism.",
  },
  {
    idx: 50,
    paragraph: 8,
    text: "이 다다의 서곡을 같이 써내려가지 않으시겠습니까?",
    en: "Shall we compose this prelude of Dada together?",
  },
  {
    idx: 51,
    paragraph: 8,
    text: "핸드폰을 높이 들어 주십시오.",
    en: "Please raise your mobile phones high.",
  },
  {
    idx: 52,
    paragraph: 8,
    text: "저를 따라 핸드폰을 높이 들어 주십시오.",
    en: "Follow me and raise your phones high.",
  },
  {
    idx: 53,
    paragraph: 8,
    text: "핸드폰의 볼륨도 키우십시오.",
    en: "And turn up the volume on your phones.",
  },
  {
    idx: 54,
    paragraph: 8,
    text: "핸드폰을 높이 들어 주십시오.",
    en: "Please raise your mobile phones high.",
  },
  {
    idx: 55,
    paragraph: 8,
    text: "다 같이 일어나 보시겠습니까?",
    en: "Shall we all stand up?",
  },
  {
    idx: 56,
    paragraph: 9,
    text: "이제 셋을 세면서 동시에 손을 모두 내리겠습니다.",
    en: "Now, as I count to three, we'll all lower our hands together.",
  },
  {
    idx: 57,
    paragraph: 9,
    text: "셋을 세면 모두 손을 내리는 겁니다.",
    en: "When I count to three, we all lower our hands.",
  },
  {
    idx: 58,
    paragraph: 9,
    text: "자 준비되셨나요?",
    en: "Are you ready?",
  },
  {
    idx: 59,
    paragraph: 9,
    text: "셋.",
    en: "Three.",
  },
  {
    idx: 60,
    paragraph: 9,
    text: "둘.",
    en: "Two.",
  },
  {
    idx: 61,
    paragraph: 9,
    text: "하나.",
    en: "One.",
  },
];
