export const SCRIPT = [
  { idx: 0, paragraph: 0, text: "보셨습니까?", en: "Did you see that?" },
  {
    idx: 1,
    paragraph: 1,
    text: "하나의 시뮬라시옹의 붕괴를.",
    en: "The collapse of a simulacrum.",
  },
  {
    idx: 2,
    paragraph: 1,
    text: "벡터화된 MBTI 성격유형의 붕괴를.",
    en: "The collapse of the vectorized MBTI personality types.",
  },
  {
    idx: 3,
    paragraph: 1,
    text: "우리는 이 벡터를 가장 현상학적인 방법으로 깨부시는 과정을 목격했습니다.",
    en: "We have witnessed the process of dismantling this vector in the most phenomenological way.",
  },
  {
    idx: 4,
    paragraph: 1,
    text: "그 어떤 알고리즘적인 대상도,",
    en: "No algorithmic construct,",
  },
  {
    idx: 5,
    paragraph: 1,
    text: "살아있는 몸의 체험 앞에서는 해체되기 마련입니다.",
    en: "Can withstand the experience of a living body; it inevitably collapses.",
  },
  {
    idx: 6,
    paragraph: 2,
    text: "그래서 저는 더 이상 언어로 소통하지 않겠습니다.",
    en: "Therefore, I will no longer communicate through language.",
  },
  {
    idx: 7,
    paragraph: 2,
    text: "언어라는 것은 일종의 사고의 감옥이기 때문입니다.",
    en: "Because language is a kind of prison for thought.",
  },
  {
    idx: 8,
    paragraph: 2,
    text: "언어를 초월한, 더 원초적이고 본능적인 소통,",
    en: "Communication that transcends language, more primal and instinctive,",
  },
  {
    idx: 9,
    paragraph: 2,
    text: "LLM(대형언어모델)이 해석할 수 없는 방식으로 소통하는것,",
    en: "Communicating in ways that Large Language Models (LLMs) cannot interpret,",
  },
  {
    idx: 10,
    paragraph: 2,
    text: "그것이야말로 진정 인간의 특권이자,",
    en: "That is truly the privilege of humanity, and",
  },
  {
    idx: 11,
    paragraph: 2,
    text: "진정한 다다이즘의 실천 아니겠습니까?",
    en: "Isn't that the true practice of Dadaism?",
  },
  {
    idx: 12,
    paragraph: 3,
    text: "저 자막을 보지 마십시오.",
    en: "Please do not read the subtitles.",
  },
  {
    idx: 13,
    paragraph: 3,
    text: "텍스트에 의존하지 마십시오.",
    en: "Do not rely on text.",
  },
  {
    idx: 14,
    paragraph: 3,
    text: "저의 비언어적 표현을,",
    en: "Focus on my nonverbal expressions,",
  },
  {
    idx: 15,
    paragraph: 3,
    text: "일종의 퍼포먼스 자체에 집중해주십시오.",
    en: "Please focus on the performance itself.",
  },
  {
    idx: 16,
    paragraph: 3,
    text: "이것이 바로 LLM을 넘어서는,",
    en: "This is precisely what transcends LLMs,",
  },
  {
    idx: 17,
    paragraph: 3,
    text: "인간적인 표현 방식이 아니겠습니까?",
    en: "Isn't this the human way of expression?",
  },
  {
    idx: 18,
    paragraph: 4,
    text: "이제 여러분을 또 다른 다다의 무대로 초대하겠습니다.",
    en: "Now, I invite you to another stage of Dada.",
  },
  {
    idx: 19,
    paragraph: 4,
    text: "핸드폰을 꺼내 주십시오.",
    en: "Please take out your mobile phones.",
  },
  {
    idx: 20,
    paragraph: 4,
    text: "핸드폰을 꺼내 QR을 스캔하십시오.",
    en: "Please take out your phones and scan the QR code.",
  },
  {
    idx: 21,
    paragraph: 4,
    text: "그리고 이름을 기입해 주십시오.",
    en: "And please enter your name.",
  },
  { idx: 22, paragraph: 5, text: "자.", en: "Now." },
  { idx: 23, paragraph: 5, text: "무엇이 보이십니까?", en: "What do you see?" },
  {
    idx: 24,
    paragraph: 5,
    text: "여러분이 보고 계신 것은 인공신경망의 구조입니다.",
    en: "What you're seeing is the structure of an artificial neural network.",
  },
  { idx: 25, paragraph: 5, text: "볼츠만 머신,", en: "Boltzmann Machines," },
  { idx: 26, paragraph: 5, text: "VAE,", en: "Variational Autoencoders," },
  { idx: 27, paragraph: 5, text: "알렉스넷,", en: "AlexNet," },
  {
    idx: 28,
    paragraph: 5,
    text: "우리가 매일같이 말하고 있는,",
    en: "These are the things we talk about daily,",
  },
  {
    idx: 29,
    paragraph: 5,
    text: "우리가 두려워하는 인공지능 모델들이 보이십니까?",
    en: "Do you see the artificial intelligence models we fear?",
  },
  {
    idx: 30,
    paragraph: 6,
    text: "이들이 진정 우리 인류보다 똑똑할까요?",
    en: "Are they truly smarter than us?",
  },
  {
    idx: 31,
    paragraph: 6,
    text: "이들이 진정 우리 인류를 대체할까요?",
    en: "Will they truly replace us?",
  },
  {
    idx: 32,
    paragraph: 6,
    text: "이들이 진정 우리 인류를 지배할까요?",
    en: "Will they truly dominate us?",
  },
  { idx: 33, paragraph: 7, text: "아닙니다.", en: "No." },
  {
    idx: 34,
    paragraph: 7,
    text: "저는 우리 인류의 인간적 특성, 예술적 특성을 믿습니다.",
    en: "I believe in the human qualities, our artistic traits.",
  },
  {
    idx: 35,
    paragraph: 7,
    text: "우리 인간이 벡터로 치환될 수 없는,",
    en: "That we humans cannot be reduced to vectors,",
  },
  {
    idx: 36,
    paragraph: 7,
    text: "숫자 그 이상의 무언가를 성취할 수 있는 존재라고 생각합니다.",
    en: "And are beings capable of achieving something beyond numbers.",
  },
  {
    idx: 37,
    paragraph: 7,
    text: "그러나 이를 위해서는 기술적 합리주의를 넘어,",
    en: "However, to do so, we must go beyond technological rationalism,",
  },
  {
    idx: 38,
    paragraph: 7,
    text: "이 인공신경망의 반듯한 유클리드-데카르트적 구조를 깨뜨릴,",
    en: "And break down the neat Euclidean-Cartesian structures of these artificial neural networks,",
  },
  {
    idx: 39,
    paragraph: 7,
    text: "다다이즘의 파괴적 힘이 필요합니다.",
    en: "We need the destructive power of Dadaism.",
  },
  {
    idx: 40,
    paragraph: 8,
    text: "이 다다의 서곡을 같이 써내려가지 않으시겠습니까?",
    en: "Shall we compose this prelude of Dada together?",
  },
  {
    idx: 41,
    paragraph: 8,
    text: "핸드폰을 높이 들어 주십시오.",
    en: "Please raise your mobile phones high.",
  },
  {
    idx: 42,
    paragraph: 8,
    text: "저를 따라 핸드폰을 높이 들어 주십시오.",
    en: "Follow me and raise your phones high.",
  },
  {
    idx: 43,
    paragraph: 8,
    text: "핸드폰의 볼륨도 키우십시오.",
    en: "And turn up the volume on your phones.",
  },
  {
    idx: 44,
    paragraph: 8,
    text: "다 같이 일어나 보시겠습니까?",
    en: "Shall we all stand up?",
  },
  {
    idx: 45,
    paragraph: 9,
    text: "이제 셋을 세면서 동시에 손을 모두 내리겠습니다.",
    en: "Now, as I count to three, we'll all lower our hands together.",
  },
  { idx: 46, paragraph: 9, text: "자 준비되셨나요?", en: "Are you ready?" },
  { idx: 47, paragraph: 9, text: "셋.", en: "Three." },
  { idx: 48, paragraph: 9, text: "둘.", en: "Two." },
  { idx: 49, paragraph: 9, text: "하나.", en: "One." },
];
