/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

const PATH = "/3d/avatars-1112/untitled.glb";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({
  position = [0, 0, 0],
  scale = [1, 1, 1],
  rotation = [0, 0, 0],
  materialColor = "#ffffff",
  metalness = 0.5,
  roughness = 0.5,
  ...props
}) {
  const group = useRef();
  const { nodes, materials } = useGLTF(PATH);

  // Apply material properties
  materials.Body.color.set(materialColor);
  materials.Body.metalness = metalness;
  materials.Body.roughness = roughness;

  materials.Head.color.set(materialColor);
  materials.Head.metalness = metalness;
  materials.Head.roughness = roughness;

  materials.Misc.color.set(materialColor);
  materials.Misc.metalness = metalness;
  materials.Misc.roughness = roughness;

  return (
    <group
      ref={group}
      position={position}
      scale={scale}
      rotation={rotation}
      {...props}
      dispose={null}
    >
      <group name="Scene">
        <group name="Armature" scale={0.01}>
          <group name="Droide_de_seguridad_Star_Wars_KX">
            <skinnedMesh
              name="Droide_de_seguridad_Star_Wars_KX_1"
              geometry={nodes.Droide_de_seguridad_Star_Wars_KX_1.geometry}
              material={materials.Body}
              skeleton={nodes.Droide_de_seguridad_Star_Wars_KX_1.skeleton}
              morphTargetDictionary={
                nodes.Droide_de_seguridad_Star_Wars_KX_1.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Droide_de_seguridad_Star_Wars_KX_1.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Droide_de_seguridad_Star_Wars_KX_2"
              geometry={nodes.Droide_de_seguridad_Star_Wars_KX_2.geometry}
              material={materials.Head}
              skeleton={nodes.Droide_de_seguridad_Star_Wars_KX_2.skeleton}
              morphTargetDictionary={
                nodes.Droide_de_seguridad_Star_Wars_KX_2.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Droide_de_seguridad_Star_Wars_KX_2.morphTargetInfluences
              }
            />
            <skinnedMesh
              name="Droide_de_seguridad_Star_Wars_KX_3"
              geometry={nodes.Droide_de_seguridad_Star_Wars_KX_3.geometry}
              material={materials.Misc}
              skeleton={nodes.Droide_de_seguridad_Star_Wars_KX_3.skeleton}
              morphTargetDictionary={
                nodes.Droide_de_seguridad_Star_Wars_KX_3.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Droide_de_seguridad_Star_Wars_KX_3.morphTargetInfluences
              }
            />
          </group>
          <primitive object={nodes.RL_BoneRoot} />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload(PATH);
