export const SCRIPT = [
  { idx: 0, paragraph: 0, text: "보셨습니까?", en: "Have you witnessed it?" },
  {
    idx: 1,
    paragraph: 1,
    text: "하나의 벡터화된 시뮬라시옹의 붕괴를.",
    en: "The disintegration of a vectorised simulacrum.",
  },
  {
    idx: 2,
    paragraph: 1,
    text: "인간을 알고리즘화하는 MBTI 성격유형의 붕괴를.",
    en: "The collapse of the MBTI personality typology that reduces humans to algorithms.",
  },
  {
    idx: 3,
    paragraph: 1,
    text: "제가 직접 Three.js, ChatGPT API, 그리고 Device Accelerometer API를 사용해 코딩한 이 멀티 디바이스 웹 작품을 통해,",
    en: "Through this Multi-Device Web Artwork that I programmed using Three.js, ChatGPT API, and the Device Accelerometer API,",
  },
  {
    idx: 4,
    paragraph: 1,
    text: "우리는 이 벡터를 가장 현상학적인 방법으로 깨부시는 과정을 목격했습니다.",
    en: "We have observed the deconstruction of this vector in the most phenomenological manner.",
  },
  {
    idx: 5,
    paragraph: 1,
    text: "그 어떤 알고리즘적인 대상도 살아있는 몸의 체험 앞에서는",
    en: "No algorithmic construct can endure when confronted with the experience of a living body.",
  },
  {
    idx: 6,
    paragraph: 1,
    text: "현상학적으로 해체되기 마련입니다.",
    en: "It is inevitably deconstructed phenomenologically.",
  },
  {
    idx: 7,
    paragraph: 2,
    text: "그래서 저는 더 이상 정립된 언어로 소통하지 않겠습니다.",
    en: "Therefore, I shall no longer communicate through established language.",
  },
  {
    idx: 8,
    paragraph: 2,
    text: "언어라는 것은 일종의 사고의 감옥이기 때문입니다.",
    en: "For language is, in essence, a prison for thought.",
  },
  {
    idx: 9,
    paragraph: 2,
    text: "기존의 정립된 언어를 초월한, 더 원초적이고 본능적인 소통,",
    en: "Communication that transcends established language—more primordial and instinctual—",
  },
  {
    idx: 10,
    paragraph: 2,
    text: "LLM(대형언어모델)이 해석할 수 없는 방식으로 소통하는것,",
    en: "Communicating in modes that Large Language Models (LLMs) are incapable of interpreting,",
  },
  {
    idx: 11,
    paragraph: 2,
    text: "그것이야말로 진정 인간의 특권이자, 진정한 다다이즘의 실천이 아니겠습니까?",
    en: "Is that not the true privilege of humanity, and the authentic practice of Dadaism?",
  },
  {
    idx: 12,
    paragraph: 3,
    text: "예컨대 진정한 AI 아트란 그저 인공지능을 이용해 예쁜 비주얼을 그려내는 것이 아닙니다.",
    en: "I am speaking.",
  },
  {
    idx: 13,
    paragraph: 3,
    text: "인공지능의 특성과 그것이 인류에 미칠 10년, 20년 후의 영향을 예술가의 시선으로 면밀히 분석하고,",
    en: "For example, true AI art is not merely about using AI to create pretty visuals.",
  },
  {
    idx: 14,
    paragraph: 3,
    text: "그것을 다시 예술적인 방식으로 풀어내는 방식이야 말로, 진정한 기술과 예술의 깊이 있는 융합이 아니겠습니까?",
    en: "And text is automatically generated based on the amplitude of my speech, rather than its semantic content.",
  },

  {
    idx: 15,
    paragraph: 3,
    text: "지금 제가 디자인한 이 인터랙션은 제가 G아티언스를 위해 코딩한 간단한 소프트웨어인데,",
    en: "Here, the meaning of my words is inconsequential.",
  },
  {
    idx: 16,
    paragraph: 3,
    text: "여기서 제 말의 뜻이 중요한 것이 아닙니다. 말의 뜻이 아닌 발화 여부에 따라 텍스트가 자동으로 생성됩니다..",
    en: "It is the very act of performance that holds significance.",
  },
  {
    idx: 17,
    paragraph: 3,
    text: "이것이 바로 LLM을 넘어서는, 기술에 기반한 진정한 다다이즘의 실천이 아니겠습니까?",
    en: "Is this not precisely what transcends LLMs and embodies the authentic practice of Dadaism - built upon technology?",
  },
  {
    idx: 18,
    paragraph: 3,
    text: "무의미한 무미건조한 다다",
    en: "Meaningless, insipid Dada.",
  },
  {
    idx: 19,
    paragraph: 3,
    text: "다다적인 다다 다다",
    en: "Dadaistic dada dada.",
  },
  {
    idx: 20,
    paragraph: 3,
    text: "혹은 백남준이 플럭서스에서 펼친것과 같은 네오-다다",
    en: "Or neo-Dadaism, as exemplified by Nam June Paik’s Fluxus movement",
  },
  {
    idx: 21,
    paragraph: 3,
    text: "다다라는 것은 다다다",
    en: "Dada is dadada.",
  },
  {
    idx: 22,
    paragraph: 3,
    text: "다다다다다다다다",
    en: "Dadadadadadada.",
  },
  {
    idx: 23,
    paragraph: 3,
    text: "다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다",
    en: "DADADADADADADADADADADADADADADADADADADADA.",
  },
  {
    idx: 24,
    paragraph: 3,
    text: "다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다 다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다 다다다다다다다다다다다다다다다다다다다다다다다 다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다 다다다다다다다다다다다다다다다다다다 다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다 다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다다 다다다다다다다다다다다다다다다다다다다다다다다다다다다 다다다다다다다다다다다다다다다다다다다다다",
    en: "DADADADADADADADADADADADADADADADADADADADA DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADAD ADADADADADADADADADADADADADADADADADADADADADADADADADAD ADADADADADADADADADADADADADADADADADADADADADADADADADADADADA DADADADADADADADADADADADADADADADA DADADADADADADADADADADADADADADADADADADADADADADADADADADADADADAD ADADADADADADADADADADADADADADADADADADADAD ADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADADA.",
  },
  {
    idx: 25,
    paragraph: 4,
    text: "이제 여러분을 또 다른 다다의 무대로 초대하겠습니다.",
    en: "Now, I shall invite you to another stage of Dada.",
  },
  {
    idx: 26,
    paragraph: 4,
    text: "핸드폰을 꺼내 주십시오.",
    en: "Please take out your mobile phones.",
  },
  {
    idx: 27,
    paragraph: 4,
    text: "핸드폰을 꺼내 QR을 스캔하십시오.",
    en: "Please take out your mobile phones and scan the QR code.",
  },
  {
    idx: 28,
    paragraph: 4,
    text: "QR코드를 스캔하십시오.",
    en: "Please scan the QR code.",
  },
  {
    idx: 29,
    paragraph: 4,
    text: "그리고 이름을 기입해 주십시오.",
    en: "And kindly enter your name.",
  },
  {
    idx: 30,
    paragraph: 5,
    text: "자.",
    en: "Well then.",
  },
  {
    idx: 31,
    paragraph: 5,
    text: "무엇이 보이십니까?",
    en: "What do you observe?",
  },
  {
    idx: 32,
    paragraph: 5,
    text: "여러분이 보고 계신 것은 인공신경망의 구조입니다.",
    en: "You are observing the structure of an artificial neural network.",
  },
  {
    idx: 33,
    paragraph: 5,
    text: "볼츠만 머신,",
    en: "Boltzmann Machines,",
  },
  {
    idx: 34,
    paragraph: 5,
    text: "VAE,",
    en: "Variational Autoencoder,",
  },
  {
    idx: 35,
    paragraph: 5,
    text: "알렉스넷,",
    en: "AlexNet,",
  },
  {
    idx: 36,
    paragraph: 5,
    text: "우리가 매일같이 말하고 있는,",
    en: "These are the topics we discuss on a daily basis,",
  },
  {
    idx: 37,
    paragraph: 5,
    text: "우리가 두려워하는 인공지능 모델들이 보이십니까?",
    en: "Do you see the artificial intelligence models we fear?",
  },
  {
    idx: 38,
    paragraph: 6,
    text: "이들이 진정 우리 인류를 대체할까요?",
    en: "Will they truly supplant humanity?",
  },
  {
    idx: 39,
    paragraph: 7,
    text: "아닙니다.",
    en: "No.",
  },
  {
    idx: 40,
    paragraph: 7,
    text: "저는 우리 인류의 인간적 특성, 예술적 특성을 믿습니다.",
    en: "I have faith in our human attributes, our artistic characteristics.",
  },
  {
    idx: 41,
    paragraph: 7,
    text: "우리 인간이 숫자 그 이상의 무언가를 성취할 수 있는 존재라고 생각합니다.",
    en: "I believe that humans are beings capable of attaining something beyond mere numbers.",
  },
  {
    idx: 42,
    paragraph: 7,
    text: "다다이즘의 파괴적 힘이 지금까지의 데카르트적 사고를 넘어서는 첫 단계가 될 수 있습니다.",
    en: "The destructive force of Dadaism may serve as the initial step in transcending Cartesian thought.",
  },
  {
    idx: 43,
    paragraph: 8,
    text: "이 다다의 서곡을 같이 써내려가지 않으시겠습니까?",
    en: "Shall we compose this prelude to Dada together?",
  },
  {
    idx: 44,
    paragraph: 8,
    text: "핸드폰을 높이 들어 주십시오.",
    en: "Please raise your mobile phones high.",
  },
  {
    idx: 45,
    paragraph: 8,
    text: "저를 따라 핸드폰을 높이 들어 주십시오.",
    en: "Follow me and raise your mobile phones high.",
  },
  {
    idx: 46,
    paragraph: 8,
    text: "핸드폰의 볼륨도 키우십시오.",
    en: "And please increase the volume on your mobile phones.",
  },
  {
    idx: 47,
    paragraph: 9,
    text: "이제 셋을 세보겠습니다.",
    en: "Now, let's count to three.",
  },
  {
    idx: 48,
    paragraph: 9,
    text: "자 준비되셨나요?",
    en: "Are you ready?",
  },
  {
    idx: 49,
    paragraph: 9,
    text: "자.",
    en: "Well then.",
  },
  {
    idx: 50,
    paragraph: 9,
    text: "셋.",
    en: "Three.",
  },
  {
    idx: 51,
    paragraph: 9,
    text: "둘.",
    en: "Two.",
  },
  {
    idx: 52,
    paragraph: 9,
    text: "하나.",
    en: "One.",
  },
  {
    idx: 53,
    paragraph: 9,
    text: "모두 손을 내리세요.",
    en: "Everyone, lower your hands.",
  },
];

export const MODEL_CHANGE = 33;
