export const TEST = [
  "저는 국가에서 육성한 수학 인재였습니다.",
  "중학교 때는 영재교육원에서,",
  "고등학교 때는 영재고에서 교육을 받았으며,",
  "대한수학회의 국가대표 육성 겨울학교를 거쳐",
  "서울대학교 산업공학과에 진학한 전형적인 이공계 엘리트였습니다.",
  "그러나 지금 이 자리에 서 있는 제 모습을 보며 의아해하실지도 모릅니다.",
  "왜 전통적인 공학도로써의 길이 아닌",
  "예술 기술 연구자로서 여러분 앞에 서게 되었는지 말입니다.",
  "그 이유는 단순합니다.",
  "장기적으로 AI가 주도하는 시대에서",
  "제가 공학 분야에서 어떤 가치를 더할 수 있을지 의문이 들었고,",
  "그 답을 예술에서 찾을 수 있다 생각했기 때문입니다.",
  "올해 노벨 화학상은 AI 연구를 기반으로 수여되었습니다.",
  "제가 고등학교 때 밤새 고민하던 KMO의 어려운 기하 문제도 이제 AI가 더 빠르고 정확하게 해결합니다.",
  "이처럼 이공계의 많은 분야가 점점 더 ‘알파고화’되고 있습니다.",
  "이 변화 속에서 인간은 무엇을 할 수 있을까요?",
  "모든 분야에서 AI가 인간을 능가하지 않을까요?",
  "저는 그렇게 생각하지 않았습니다.",
  "인간만이 할 수 있는 무언가가 반드시 존재한다고 믿었고,",
  "그 답을 예술에서 찾았습니다.",
  "기계는 합리적이고 계산적입니다.",
  "확률에 기반한 AI는 뛰어난 논리와 효율성으로 항상 최적의 결과를 도출합니다.",
  "반면, 인간은 비합리적이고, 예측할 수 없으며, 실수투성이입니다.",
  "때로는 감정에 휘둘려 논리를 벗어나기도 합니다.",
  "하지만 저는 바로 이러한 인간의 비완전성이야말로 우리의 가장 큰 강점이라고 깨달았습니다.",
  "산업혁명 이후 비합리성은 오랫동안 인간의 단점으로 여겨졌습니다.",
  "하지만 AI의 시대가 도래한 지금, 비합리성은 오히려 인간을 AI와 구분짓는 가장 고유한 특징으로 자리 잡았습니다.",
  "이 비논리성과 비합리성, 그리고 예측 불가능성은 바로 인간 존재의 이유이며,",
  "그것을 육성하는 것이 인류의 미래라고 믿습니다.",
  "그렇습니다.",
  "우리 인류는 더욱 예술적이어야 합니다.",
  "더 창의적이고, 무엇보다도 더 다양해야 합니다.",
  "그러나 제가 목격하고 있는 동시대의 상황은 정반대입니다.",
  "우리는 스스로를 숫자와 데이터로 환원시키며, 기계처럼 표준화되는 것을 자처하고 있습니다.",
  "가장 단적인 예가 MBTI와 같은 심리 테스트입니다.",
  "우리는 단지 네 글자의 코드로 자신을 정의하며,",
  "인간 고유의 복잡성과 다양성을 단순화하고 축소하려 합니다.",
  "이런 표준화는 마치 기계가 우리를 더 쉽게 이해하고 분류할 수 있도록 돕는 과정처럼 보입니다.",
  "하지만 그것은 결국 우리를 더 인간답지 않게 만들며,",
  "인간성과 기계의 차이를 점점 더 모호하게 만드는 선택일 뿐입니다.",
  "저는 이러한 현실에 질문을 던지고,",
  "인간만이 가진 고유한 가치를 탐구하기 위해 예술로 향했습니다.",
  "예술은 단순한 창작을 넘어,",
  "인간의 비합리적이고 예측 불가능한 본질을 기념하는 영역입니다.",
  "AI가 아무리 똑똑해도, 인간의 감정과 엉뚱함에서 비롯된 창조적 순간을 복제할 수는 없습니다.",
  "이것이 바로 AI 시대에서도 인간이 빛날 수 있는 이유입니다.",
  "이제 우리에게 필요한 것은 더욱 예술적이고 다채로운 존재가 되는 것입니다.",
  "비합리성과 비논리성을 우리의 강점으로 받아들이고,",
  "기계와는 다른 방식으로 스스로를 확장해 나가야 합니다.",
  "그것이 우리가 AI 시대에서 인간다움을 지켜낼 수 있는 유일한 길입니다.",
];

export const SCRIPT = [
  { idx: 0, paragraph: 0, text: "보셨습니까?", en: "Did you see that?" },
  {
    idx: 1,
    paragraph: 1,
    text: "하나의 시뮬라시옹의 붕괴를.",
    en: "The collapse of a simulacrum.",
  },
  {
    idx: 2,
    paragraph: 1,
    text: "벡터화된 MBTI 성격유형의 붕괴를.",
    en: "The collapse of the vectorized MBTI personality types.",
  },
  {
    idx: 3,
    paragraph: 1,
    text: "우리는 이 벡터를 가장 현상학적인 방법으로 깨부시는 과정을 목격했습니다.",
    en: "We have witnessed the process of dismantling this vector in the most phenomenological way.",
  },
  {
    idx: 4,
    paragraph: 1,
    text: "그 어떤 알고리즘적인 대상도,",
    en: "No algorithmic construct,",
  },
  {
    idx: 5,
    paragraph: 1,
    text: "살아있는 몸의 체험 앞에서는 해체되기 마련입니다.",
    en: "Can withstand the experience of a living body; it inevitably collapses.",
  },
  {
    idx: 6,
    paragraph: 2,
    text: "그래서 저는 더 이상 언어로 소통하지 않겠습니다.",
    en: "Therefore, I will no longer communicate through language.",
  },
  {
    idx: 7,
    paragraph: 2,
    text: "언어라는 것은 일종의 사고의 감옥이기 때문입니다.",
    en: "Because language is a kind of prison for thought.",
  },
  {
    idx: 8,
    paragraph: 2,
    text: "언어를 초월한, 더 원초적이고 본능적인 소통,",
    en: "Communication that transcends language, more primal and instinctive,",
  },
  {
    idx: 9,
    paragraph: 2,
    text: "LLM(대형언어모델)이 해석할 수 없는 방식으로 소통하는것,",
    en: "Communicating in ways that Large Language Models (LLMs) cannot interpret,",
  },
  {
    idx: 10,
    paragraph: 2,
    text: "그것이야말로 진정 인간의 특권이자,",
    en: "That is truly the privilege of humanity, and",
  },
  {
    idx: 11,
    paragraph: 2,
    text: "진정한 다다이즘의 실천 아니겠습니까?",
    en: "Isn't that the true practice of Dadaism?",
  },
  {
    idx: 12,
    paragraph: 3,
    text: "저 자막을 보지 마십시오.",
    en: "Please do not read the subtitles.",
  },
  {
    idx: 13,
    paragraph: 3,
    text: "텍스트에 의존하지 마십시오.",
    en: "Do not rely on text.",
  },
  {
    idx: 14,
    paragraph: 3,
    text: "저의 비언어적 표현을,",
    en: "Focus on my nonverbal expressions,",
  },
  {
    idx: 15,
    paragraph: 3,
    text: "일종의 퍼포먼스 자체에 집중해주십시오.",
    en: "Please focus on the performance itself.",
  },
  {
    idx: 16,
    paragraph: 3,
    text: "이것이 바로 LLM을 넘어서는,",
    en: "This is precisely what transcends LLMs,",
  },
  {
    idx: 17,
    paragraph: 3,
    text: "인간적인 표현 방식이 아니겠습니까?",
    en: "Isn't this the human way of expression?",
  },
  {
    idx: 18,
    paragraph: 4,
    text: "이제 여러분을 또 다른 다다의 무대로 초대하겠습니다.",
    en: "Now, I invite you to another stage of Dada.",
  },
  {
    idx: 19,
    paragraph: 4,
    text: "핸드폰을 꺼내 주십시오.",
    en: "Please take out your mobile phones.",
  },
  {
    idx: 20,
    paragraph: 4,
    text: "핸드폰을 꺼내 QR을 스캔하십시오.",
    en: "Please take out your phones and scan the QR code.",
  },
  {
    idx: 21,
    paragraph: 4,
    text: "그리고 이름을 기입해 주십시오.",
    en: "And please enter your name.",
  },
  { idx: 22, paragraph: 5, text: "자.", en: "Now." },
  { idx: 23, paragraph: 5, text: "무엇이 보이십니까?", en: "What do you see?" },
  {
    idx: 24,
    paragraph: 5,
    text: "여러분이 보고 계신 것은 인공신경망의 구조입니다.",
    en: "What you're seeing is the structure of an artificial neural network.",
  },
  { idx: 25, paragraph: 5, text: "볼츠만 머신,", en: "Boltzmann Machines," },
  { idx: 26, paragraph: 5, text: "VAE,", en: "Variational Autoencoders," },
  { idx: 27, paragraph: 5, text: "알렉스넷,", en: "AlexNet," },
  {
    idx: 28,
    paragraph: 5,
    text: "우리가 매일같이 말하고 있는,",
    en: "These are the things we talk about daily,",
  },
  {
    idx: 29,
    paragraph: 5,
    text: "우리가 두려워하는 인공지능 모델들이 보이십니까?",
    en: "Do you see the artificial intelligence models we fear?",
  },
  {
    idx: 30,
    paragraph: 6,
    text: "이들이 진정 우리 인류보다 똑똑할까요?",
    en: "Are they truly smarter than us?",
  },
  {
    idx: 31,
    paragraph: 6,
    text: "이들이 진정 우리 인류를 대체할까요?",
    en: "Will they truly replace us?",
  },
  {
    idx: 32,
    paragraph: 6,
    text: "이들이 진정 우리 인류를 지배할까요?",
    en: "Will they truly dominate us?",
  },
  { idx: 33, paragraph: 7, text: "아닙니다.", en: "No." },
  {
    idx: 34,
    paragraph: 7,
    text: "저는 우리 인류의 인간적 특성, 예술적 특성을 믿습니다.",
    en: "I believe in the human qualities, our artistic traits.",
  },
  {
    idx: 35,
    paragraph: 7,
    text: "우리 인간이 벡터로 치환될 수 없는,",
    en: "That we humans cannot be reduced to vectors,",
  },
  {
    idx: 36,
    paragraph: 7,
    text: "숫자 그 이상의 무언가를 성취할 수 있는 존재라고 생각합니다.",
    en: "And are beings capable of achieving something beyond numbers.",
  },
  {
    idx: 37,
    paragraph: 7,
    text: "그러나 이를 위해서는 기술적 합리주의를 넘어,",
    en: "However, to do so, we must go beyond technological rationalism,",
  },
  {
    idx: 38,
    paragraph: 7,
    text: "이 인공신경망의 반듯한 유클리드-데카르트적 구조를 깨뜨릴,",
    en: "And break down the neat Euclidean-Cartesian structures of these artificial neural networks,",
  },
  {
    idx: 39,
    paragraph: 7,
    text: "다다이즘의 파괴적 힘이 필요합니다.",
    en: "We need the destructive power of Dadaism.",
  },
  {
    idx: 40,
    paragraph: 8,
    text: "이 다다의 서곡을 같이 써내려가지 않으시겠습니까?",
    en: "Shall we compose this prelude of Dada together?",
  },
  {
    idx: 41,
    paragraph: 8,
    text: "핸드폰을 높이 들어 주십시오.",
    en: "Please raise your mobile phones high.",
  },
  {
    idx: 42,
    paragraph: 8,
    text: "저를 따라 핸드폰을 높이 들어 주십시오.",
    en: "Follow me and raise your phones high.",
  },
  {
    idx: 43,
    paragraph: 8,
    text: "핸드폰의 볼륨도 키우십시오.",
    en: "And turn up the volume on your phones.",
  },
  {
    idx: 44,
    paragraph: 8,
    text: "다 같이 일어나 보시겠습니까?",
    en: "Shall we all stand up?",
  },
  {
    idx: 45,
    paragraph: 9,
    text: "이제 셋을 세면서 동시에 손을 모두 내리겠습니다.",
    en: "Now, as I count to three, we'll all lower our hands together.",
  },
  { idx: 46, paragraph: 9, text: "자 준비되셨나요?", en: "Are you ready?" },
  { idx: 47, paragraph: 9, text: "셋.", en: "Three." },
  { idx: 48, paragraph: 9, text: "둘.", en: "Two." },
  { idx: 49, paragraph: 9, text: "하나.", en: "One." },
];
